{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "GoToAssist Corporate",
    "description": "TODO: Add Description",
    "contact": {}
  },
  "host": "api.getgo.com",
  "basePath": "/G2AC/rest/v1",
  "schemes": [
    "https"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/representatives": {
      "get": {
        "summary": "Representatives",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "post": {
        "summary": "Representative",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesPost",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RepresentativeRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/representatives/pages": {
      "get": {
        "summary": "Representatives with paging",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesPagesGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/representatives/{representativeKey}": {
      "get": {
        "summary": "Representative",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesByRepresentativeKeyGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "representativeKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "Representative",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesByRepresentativeKeyPut",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/RepresentativeRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "representativeKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "delete": {
        "summary": "Representative",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesByRepresentativeKeyDelete",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "representativeKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/representatives/{representativeKey}/portals": {
      "get": {
        "summary": "Representative portals",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesPortalsByRepresentativeKeyGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "representativeKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "Representative portals",
        "tags": [
          "Representatives"
        ],
        "operationId": "RepresentativesPortalsByRepresentativeKeyPut",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "type": "array",
              "items": {
                "$ref": "#/definitions/RepresentativeportalsRequest"
              }
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "representativeKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/teams": {
      "get": {
        "summary": "Teams",
        "tags": [
          "Teams"
        ],
        "operationId": "TeamsGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "post": {
        "summary": "Team",
        "tags": [
          "Teams"
        ],
        "operationId": "TeamsPost",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/TeamRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/teams/pages": {
      "get": {
        "summary": "Teams with paging",
        "tags": [
          "Teams"
        ],
        "operationId": "TeamsPagesGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/teams/{teamKey}": {
      "get": {
        "summary": "Team",
        "tags": [
          "Teams"
        ],
        "operationId": "TeamsByTeamKeyGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "teamKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "put": {
        "summary": "Team",
        "tags": [
          "Teams"
        ],
        "operationId": "TeamsByTeamKeyPut",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/TeamRequest"
            }
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "teamKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      },
      "delete": {
        "summary": "Team",
        "tags": [
          "Teams"
        ],
        "operationId": "TeamsByTeamKeyDelete",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "teamKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/portals": {
      "get": {
        "summary": "Portals",
        "tags": [
          "Portals"
        ],
        "operationId": "PortalsGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/portals/pages": {
      "get": {
        "summary": "Portals with paging",
        "tags": [
          "Portals"
        ],
        "operationId": "PortalsPagesGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/portals/{portalKey}": {
      "get": {
        "summary": "Portal",
        "tags": [
          "Portals"
        ],
        "operationId": "PortalsByPortalKeyGet",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "portalKey",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "RepresentativeRequest": {
      "title": "RepresentativeRequest",
      "example": {
        "login": "string",
        "password": "string",
        "firstName": "string",
        "lastName": "string",
        "nickName": "string",
        "custom": "string",
        "teamKey": 0
      },
      "type": "object",
      "properties": {
        "login": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "nickName": {
          "type": "string"
        },
        "custom": {
          "type": "string"
        },
        "teamKey": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "login",
        "password",
        "firstName",
        "lastName",
        "nickName",
        "custom",
        "teamKey"
      ]
    },
    "RepresentativeportalsRequest": {
      "title": "RepresentativeportalsRequest",
      "example": {
        "portalKey": 0,
        "portalName": "string",
        "parentKey": 0,
        "subPortalKeys": [
          0
        ],
        "portalType": "PhoneModeEnhanced"
      },
      "type": "object",
      "properties": {
        "portalKey": {
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "portalName": {
          "example": "string",
          "type": "string"
        },
        "parentKey": {
          "example": 0,
          "type": "integer",
          "format": "int32"
        },
        "subPortalKeys": {
          "example": [
            0
          ],
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        },
        "portalType": {
          "example": "PhoneModeEnhanced",
          "type": "string"
        }
      },
      "required": [
        "portalKey",
        "portalName",
        "parentKey",
        "subPortalKeys",
        "portalType"
      ]
    },
    "TeamRequest": {
      "title": "TeamRequest",
      "example": {
        "teamName": "string",
        "parentKey": 0,
        "portalKey": 0,
        "subPortalKeys": [
          0
        ]
      },
      "type": "object",
      "properties": {
        "teamName": {
          "type": "string"
        },
        "parentKey": {
          "type": "integer",
          "format": "int32"
        },
        "portalKey": {
          "type": "integer",
          "format": "int32"
        },
        "subPortalKeys": {
          "type": "array",
          "items": {
            "type": "integer",
            "format": "int32"
          }
        }
      },
      "required": [
        "teamName",
        "parentKey",
        "portalKey",
        "subPortalKeys"
      ]
    }
  },
  "tags": [
    {
      "name": "Representatives",
      "description": ""
    },
    {
      "name": "Teams",
      "description": ""
    },
    {
      "name": "Portals",
      "description": ""
    }
  ]
}