{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "QuickBooks Online API Orchestrated API Collections",
    "description": "This collection contains 5 Orchestrated samples of common QBO use cases.\n\nCreate Receipt - This orchestration contains the following flow of calls.  1. Create a customer 2.  Create an item  3. Create a reciept for the transaction between the customer and the item.\n\nCreate Payment - This orchestration contains the following flow of calls.  1. Create a customer 2.  Create an item  3. Create an invoice for a transaction between the customer and the item.  4. Create payment for the amount owed on invoice\n\nCreate an Expense - This orchestration contains the following flow of calls.  1. Create a bank account 2. Create an expense account 3. Create a purchase expense linked to the bank account\n\nCreate an Invoice - This orchestration contains the following flow of calls.  1. Create a customer 2.  Create an item  3. Create an invoice for a transaction between the customer and the item.\n\nPay Bills - This orchestration contains the following flow of calls.  1. Create an account 2.  Create a vendor  3. Create an bill for a vendor and the account created  4. Create a payment for the bill",
    "contact": {}
  },
  "host": "example.com",
  "basePath": "/v3/company/DefaultParameterValue",
  "securityDefinitions": {
    "auth": {
      "type": "oauth2",
      "flow": "implicit",
      "authorizationUrl": "http://example.com/auth",
      "scopes": {}
    }
  },
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/bill": {
      "post": {
        "description": "Create a bill\nContent-Type:application/json\nMethod - POST",
        "summary": "Bill-Create",
        "tags": [
          "Create a BillPayment against a Vendor's Bill"
        ],
        "operationId": "Bill-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Bill-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/account": {
      "post": {
        "description": "Create a new Check Account",
        "summary": "CC Account-Create",
        "tags": [
          "Create a BillPayment against a Vendor's Bill"
        ],
        "operationId": "CCAccount-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CCAccount-CreateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/vendor": {
      "post": {
        "description": "Create a vendor object\nMethod : POST\n\n",
        "summary": "Vendor-Create",
        "tags": [
          "Create a BillPayment against a Vendor's Bill"
        ],
        "operationId": "Vendor-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Vendor-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/billpayment": {
      "post": {
        "description": "Create a BillPayment against a pre-created bill\nContent-Type:application/json\nMethod - POST",
        "summary": "BillPayment-Create",
        "tags": [
          "Create a BillPayment against a Vendor's Bill"
        ],
        "operationId": "BillPayment-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/BillPayment-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/invoice": {
      "post": {
        "description": "POST: Create an Invoice",
        "summary": "Invoice-Create",
        "tags": [
          "Create a ReceivePayment against a Customer's Invoice"
        ],
        "operationId": "Invoice-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Invoice-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/customer": {
      "post": {
        "description": "Create a customer\nMethod : POST",
        "summary": "Customer-Create",
        "tags": [
          "Create a ReceivePayment against a Customer's Invoice"
        ],
        "operationId": "Customer-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Customer-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/item": {
      "post": {
        "description": "POST: Create an Item",
        "summary": "Item-Create",
        "tags": [
          "Create a ReceivePayment against a Customer's Invoice"
        ],
        "operationId": "Item-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Item-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/payment": {
      "post": {
        "description": "Create an payment object\nMethod : POST\n",
        "summary": "Payment-Create",
        "tags": [
          "Create a ReceivePayment against a Customer's Invoice"
        ],
        "operationId": "Payment-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Payment-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/salesreceipt": {
      "post": {
        "summary": "Reciept-Create",
        "tags": [
          "Create a SalesReceipt for a Customer"
        ],
        "operationId": "Reciept-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Reciept-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/timeactivity": {
      "post": {
        "summary": "TimeActivity-Create",
        "tags": [
          "Create a Time-Activity for an Employee"
        ],
        "operationId": "TimeActivity-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/TimeActivity-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/employee": {
      "post": {
        "summary": "Employee-Create",
        "tags": [
          "Create a Time-Activity for an Employee"
        ],
        "operationId": "Employee-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Employee-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/purchase": {
      "post": {
        "description": "Create a puchase object\nMethod : POST\n",
        "summary": "Purchase-Create",
        "tags": [
          "Create an Expense for a Vendor"
        ],
        "operationId": "Purchase-Create",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "consumes": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "minorversion",
            "in": "query",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "User-Agent",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/Purchase-Create-Request"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "Bill-Create-Request": {
      "title": "Bill-Create-Request",
      "example": {
        "Line": [
          {
            "Id": "1",
            "Amount": 200.0,
            "DetailType": "AccountBasedExpenseLineDetail",
            "AccountBasedExpenseLineDetail": {
              "AccountRef": {
                "value": "{{AccountId}}"
              }
            }
          }
        ],
        "VendorRef": {
          "value": "{{VendorId}}"
        }
      },
      "type": "object",
      "properties": {
        "Line": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Line"
          }
        },
        "VendorRef": {
          "$ref": "#/definitions/VendorRef"
        }
      },
      "required": [
        "Line",
        "VendorRef"
      ]
    },
    "Line": {
      "title": "Line",
      "example": {
        "Id": "1",
        "Amount": 200.0,
        "DetailType": "AccountBasedExpenseLineDetail",
        "AccountBasedExpenseLineDetail": {
          "AccountRef": {
            "value": "{{AccountId}}"
          }
        }
      },
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        },
        "Amount": {
          "type": "number",
          "format": "double"
        },
        "DetailType": {
          "type": "string"
        },
        "AccountBasedExpenseLineDetail": {
          "$ref": "#/definitions/AccountBasedExpenseLineDetail"
        }
      },
      "required": [
        "Id",
        "Amount",
        "DetailType",
        "AccountBasedExpenseLineDetail"
      ]
    },
    "AccountBasedExpenseLineDetail": {
      "title": "AccountBasedExpenseLineDetail",
      "example": {
        "AccountRef": {
          "value": "{{AccountId}}"
        }
      },
      "type": "object",
      "properties": {
        "AccountRef": {
          "$ref": "#/definitions/AccountRef"
        }
      },
      "required": [
        "AccountRef"
      ]
    },
    "AccountRef": {
      "title": "AccountRef",
      "example": {
        "value": "{{AccountId}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "VendorRef": {
      "title": "VendorRef",
      "example": {
        "value": "{{VendorId}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "CCAccount-CreateRequest": {
      "title": "CCAccount-CreateRequest",
      "example": {
        "Name": "CreditCardAccount - {{$guid}}",
        "SubAccount": false,
        "FullyQualifiedName": "Mastercard",
        "Active": true,
        "Classification": "Liability",
        "AccountType": "Credit Card",
        "AccountSubType": "CreditCard",
        "CurrentBalance": 100.0,
        "CurrentBalanceWithSubAccounts": 100.0,
        "domain": "QBO",
        "sparse": false
      },
      "type": "object",
      "properties": {
        "Name": {
          "type": "string"
        },
        "SubAccount": {
          "type": "boolean"
        },
        "FullyQualifiedName": {
          "type": "string"
        },
        "Active": {
          "type": "boolean"
        },
        "Classification": {
          "type": "string"
        },
        "AccountType": {
          "type": "string"
        },
        "AccountSubType": {
          "type": "string"
        },
        "CurrentBalance": {
          "type": "number",
          "format": "double"
        },
        "CurrentBalanceWithSubAccounts": {
          "type": "number",
          "format": "double"
        },
        "domain": {
          "type": "string"
        },
        "sparse": {
          "type": "boolean"
        }
      },
      "required": [
        "Name",
        "SubAccount",
        "FullyQualifiedName",
        "Active",
        "Classification",
        "AccountType",
        "AccountSubType",
        "CurrentBalance",
        "CurrentBalanceWithSubAccounts",
        "domain",
        "sparse"
      ]
    },
    "Vendor-Create-Request": {
      "title": "Vendor-Create-Request",
      "example": {
        "DisplayName": "VendorName - {{$guid}}"
      },
      "type": "object",
      "properties": {
        "DisplayName": {
          "type": "string"
        }
      },
      "required": [
        "DisplayName"
      ]
    },
    "BillPayment-Create-Request": {
      "title": "BillPayment-Create-Request",
      "example": {
        "VendorRef": {
          "value": "{{VendorId}}",
          "name": "{{VendorName}}"
        },
        "PayType": "CreditCard",
        "CreditCardPayment": {
          "CCAccountRef": {
            "value": "{{CCAccountId}}",
            "name": "{{CCAccountName}}"
          }
        },
        "TotalAmt": 100.0,
        "PrivateNote": "Acct. 1JK90",
        "Line": [
          {
            "Amount": 100.0,
            "LinkedTxn": [
              {
                "TxnId": "{{BillId}}",
                "TxnType": "Bill"
              }
            ]
          }
        ]
      },
      "type": "object",
      "properties": {
        "VendorRef": {
          "$ref": "#/definitions/VendorRef1"
        },
        "PayType": {
          "type": "string"
        },
        "CreditCardPayment": {
          "$ref": "#/definitions/CreditCardPayment"
        },
        "TotalAmt": {
          "type": "number",
          "format": "double"
        },
        "PrivateNote": {
          "type": "string"
        },
        "Line": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Line1"
          }
        }
      },
      "required": [
        "VendorRef",
        "PayType",
        "CreditCardPayment",
        "TotalAmt",
        "PrivateNote",
        "Line"
      ]
    },
    "VendorRef1": {
      "title": "VendorRef1",
      "example": {
        "value": "{{VendorId}}",
        "name": "{{VendorName}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "name"
      ]
    },
    "CreditCardPayment": {
      "title": "CreditCardPayment",
      "example": {
        "CCAccountRef": {
          "value": "{{CCAccountId}}",
          "name": "{{CCAccountName}}"
        }
      },
      "type": "object",
      "properties": {
        "CCAccountRef": {
          "$ref": "#/definitions/CCAccountRef"
        }
      },
      "required": [
        "CCAccountRef"
      ]
    },
    "CCAccountRef": {
      "title": "CCAccountRef",
      "example": {
        "value": "{{CCAccountId}}",
        "name": "{{CCAccountName}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "name"
      ]
    },
    "Line1": {
      "title": "Line1",
      "example": {
        "Amount": 100.0,
        "LinkedTxn": [
          {
            "TxnId": "{{BillId}}",
            "TxnType": "Bill"
          }
        ]
      },
      "type": "object",
      "properties": {
        "Amount": {
          "type": "number",
          "format": "double"
        },
        "LinkedTxn": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LinkedTxn"
          }
        }
      },
      "required": [
        "Amount",
        "LinkedTxn"
      ]
    },
    "LinkedTxn": {
      "title": "LinkedTxn",
      "example": {
        "TxnId": "{{BillId}}",
        "TxnType": "Bill"
      },
      "type": "object",
      "properties": {
        "TxnId": {
          "type": "string"
        },
        "TxnType": {
          "type": "string"
        }
      },
      "required": [
        "TxnId",
        "TxnType"
      ]
    },
    "Account-Create-Request": {
      "title": "Account-Create-Request",
      "example": {
        "AccountType": "Expense",
        "Name": "ExpenseAccount - {{$guid}}"
      },
      "type": "object",
      "properties": {
        "AccountType": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": [
        "AccountType",
        "Name"
      ]
    },
    "Invoice-Create-Request": {
      "title": "Invoice-Create-Request",
      "example": {
        "Line": [
          {
            "Amount": 100.0,
            "DetailType": "SalesItemLineDetail",
            "SalesItemLineDetail": {
              "ItemRef": {
                "value": "{{ItemId}}",
                "name": "{{ItemName}}"
              },
              "Qty": 1
            }
          }
        ],
        "CustomerRef": {
          "value": "{{CustomerId}}"
        }
      },
      "type": "object",
      "properties": {
        "Line": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Line2"
          }
        },
        "CustomerRef": {
          "$ref": "#/definitions/CustomerRef"
        }
      },
      "required": [
        "Line",
        "CustomerRef"
      ]
    },
    "Line2": {
      "title": "Line2",
      "example": {
        "Amount": 100.0,
        "DetailType": "SalesItemLineDetail",
        "SalesItemLineDetail": {
          "ItemRef": {
            "value": "{{ItemId}}",
            "name": "{{ItemName}}"
          },
          "Qty": 1
        }
      },
      "type": "object",
      "properties": {
        "Amount": {
          "type": "number",
          "format": "double"
        },
        "DetailType": {
          "type": "string"
        },
        "SalesItemLineDetail": {
          "$ref": "#/definitions/SalesItemLineDetail"
        }
      },
      "required": [
        "Amount",
        "DetailType",
        "SalesItemLineDetail"
      ]
    },
    "SalesItemLineDetail": {
      "title": "SalesItemLineDetail",
      "example": {
        "ItemRef": {
          "value": "{{ItemId}}",
          "name": "{{ItemName}}"
        },
        "Qty": 1
      },
      "type": "object",
      "properties": {
        "ItemRef": {
          "$ref": "#/definitions/ItemRef"
        },
        "Qty": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "ItemRef",
        "Qty"
      ]
    },
    "ItemRef": {
      "title": "ItemRef",
      "example": {
        "value": "{{ItemId}}",
        "name": "{{ItemName}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "name"
      ]
    },
    "CustomerRef": {
      "title": "CustomerRef",
      "example": {
        "value": "{{CustomerId}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "Customer-Create-Request": {
      "title": "Customer-Create-Request",
      "example": {
        "DisplayName": "CustomerName - {{$guid}}"
      },
      "type": "object",
      "properties": {
        "DisplayName": {
          "type": "string"
        }
      },
      "required": [
        "DisplayName"
      ]
    },
    "Item-Create-Request": {
      "title": "Item-Create-Request",
      "example": {
        "Name": "SerivceItem - {{$guid}}",
        "IncomeAccountRef": {
          "value": "1",
          "name": "Services"
        },
        "Type": "Service"
      },
      "type": "object",
      "properties": {
        "Name": {
          "type": "string"
        },
        "IncomeAccountRef": {
          "$ref": "#/definitions/IncomeAccountRef"
        },
        "Type": {
          "type": "string"
        }
      },
      "required": [
        "Name",
        "IncomeAccountRef",
        "Type"
      ]
    },
    "IncomeAccountRef": {
      "title": "IncomeAccountRef",
      "example": {
        "value": "1",
        "name": "Services"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "name"
      ]
    },
    "Payment-Create-Request": {
      "title": "Payment-Create-Request",
      "example": {
        "CustomerRef": {
          "value": "{{CustomerId}}",
          "name": "{{CustomerName}}"
        },
        "TotalAmt": 100.0,
        "Line": [
          {
            "Amount": 100.0,
            "LinkedTxn": [
              {
                "TxnId": "{{InvoiceId}}",
                "TxnType": "Invoice"
              }
            ]
          }
        ]
      },
      "type": "object",
      "properties": {
        "CustomerRef": {
          "$ref": "#/definitions/CustomerRef1"
        },
        "TotalAmt": {
          "type": "number",
          "format": "double"
        },
        "Line": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Line1"
          }
        }
      },
      "required": [
        "CustomerRef",
        "TotalAmt",
        "Line"
      ]
    },
    "CustomerRef1": {
      "title": "CustomerRef1",
      "example": {
        "value": "{{CustomerId}}",
        "name": "{{CustomerName}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "name"
      ]
    },
    "Reciept-Create-Request": {
      "title": "Reciept-Create-Request",
      "example": {
        "Line": [
          {
            "Id": "1",
            "LineNum": 1,
            "Description": "Sold item",
            "Amount": 1000,
            "DetailType": "SalesItemLineDetail",
            "SalesItemLineDetail": {
              "ItemRef": {
                "value": "{{ItemId}}",
                "name": "{{ItemName}}"
              },
              "UnitPrice": 1000,
              "Qty": 1,
              "TaxCodeRef": {
                "value": "NON"
              }
            }
          },
          {
            "Amount": 1000,
            "DetailType": "SubTotalLineDetail",
            "SubTotalLineDetail": {}
          }
        ],
        "CustomerRef": {
          "value": "{{CustomerId}}",
          "name": "{{CustomerDisplayName}}"
        }
      },
      "type": "object",
      "properties": {
        "Line": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Line4"
          }
        },
        "CustomerRef": {
          "$ref": "#/definitions/CustomerRef1"
        }
      },
      "required": [
        "Line",
        "CustomerRef"
      ]
    },
    "Line4": {
      "title": "Line4",
      "example": {
        "Id": "1",
        "LineNum": 1,
        "Description": "Sold item",
        "Amount": 1000,
        "DetailType": "SalesItemLineDetail",
        "SalesItemLineDetail": {
          "ItemRef": {
            "value": "{{ItemId}}",
            "name": "{{ItemName}}"
          },
          "UnitPrice": 1000,
          "Qty": 1,
          "TaxCodeRef": {
            "value": "NON"
          }
        }
      },
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        },
        "LineNum": {
          "type": "integer",
          "format": "int32"
        },
        "Description": {
          "type": "string"
        },
        "Amount": {
          "type": "integer",
          "format": "int32"
        },
        "DetailType": {
          "type": "string"
        },
        "SalesItemLineDetail": {
          "$ref": "#/definitions/SalesItemLineDetail1"
        },
        "SubTotalLineDetail": {
          "type": "object"
        }
      },
      "required": [
        "Amount",
        "DetailType"
      ]
    },
    "SalesItemLineDetail1": {
      "title": "SalesItemLineDetail1",
      "example": {
        "ItemRef": {
          "value": "{{ItemId}}",
          "name": "{{ItemName}}"
        },
        "UnitPrice": 1000,
        "Qty": 1,
        "TaxCodeRef": {
          "value": "NON"
        }
      },
      "type": "object",
      "properties": {
        "ItemRef": {
          "$ref": "#/definitions/ItemRef"
        },
        "UnitPrice": {
          "type": "integer",
          "format": "int32"
        },
        "Qty": {
          "type": "integer",
          "format": "int32"
        },
        "TaxCodeRef": {
          "$ref": "#/definitions/TaxCodeRef"
        }
      },
      "required": [
        "ItemRef",
        "UnitPrice",
        "Qty",
        "TaxCodeRef"
      ]
    },
    "TaxCodeRef": {
      "title": "TaxCodeRef",
      "example": {
        "value": "NON"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "TimeActivity-Create-Request": {
      "title": "TimeActivity-Create-Request",
      "example": {
        "NameOf": "Employee",
        "EmployeeRef": {
          "value": "{{EmployeeId}}",
          "name": "{{EmployeeName}}"
        },
        "BillableStatus": "Billable",
        "HourlyRate": "20",
        "CustomerRef": {
          "value": "{{CustomerId}}"
        },
        "Hours": 3
      },
      "type": "object",
      "properties": {
        "NameOf": {
          "type": "string"
        },
        "EmployeeRef": {
          "$ref": "#/definitions/EmployeeRef"
        },
        "BillableStatus": {
          "type": "string"
        },
        "HourlyRate": {
          "type": "string"
        },
        "CustomerRef": {
          "$ref": "#/definitions/CustomerRef"
        },
        "Hours": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "NameOf",
        "EmployeeRef",
        "BillableStatus",
        "HourlyRate",
        "CustomerRef",
        "Hours"
      ]
    },
    "EmployeeRef": {
      "title": "EmployeeRef",
      "example": {
        "value": "{{EmployeeId}}",
        "name": "{{EmployeeName}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "name"
      ]
    },
    "Employee-Create-Request": {
      "title": "Employee-Create-Request",
      "example": {
        "GivenName": "GivenName - {{$timestamp}}",
        "FamilyName": "FamilyName - {{$timestamp}}"
      },
      "type": "object",
      "properties": {
        "GivenName": {
          "type": "string"
        },
        "FamilyName": {
          "type": "string"
        }
      },
      "required": [
        "GivenName",
        "FamilyName"
      ]
    },
    "Invoice-Create-Request1": {
      "title": "Invoice-Create-Request1",
      "example": {
        "LinkedTxn": [
          {
            "TxnId": "{{TimeActivityId}}",
            "TxnType": "TimeActivity"
          }
        ],
        "Line": [
          {
            "Id": "1",
            "LineNum": 1,
            "Description": "An employee has worked 3 hours for a customer at an hourly rate of 20",
            "Amount": "{{Amount}}",
            "DetailType": "SalesItemLineDetail",
            "SalesItemLineDetail": {
              "ItemRef": {
                "value": "{{ItemRefValue}}",
                "name": "{{ItemRefName}}"
              },
              "UnitPrice": "{{HourlyRate}}",
              "Qty": "{{HoursWorked}}"
            }
          },
          {
            "DetailType": "SubTotalLineDetail",
            "SubTotalLineDetail": {}
          }
        ],
        "CustomerRef": {
          "value": "{{CustomerId}}"
        }
      },
      "type": "object",
      "properties": {
        "LinkedTxn": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/LinkedTxn"
          }
        },
        "Line": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Line5"
          }
        },
        "CustomerRef": {
          "$ref": "#/definitions/CustomerRef"
        }
      },
      "required": [
        "LinkedTxn",
        "Line",
        "CustomerRef"
      ]
    },
    "Line5": {
      "title": "Line5",
      "example": {
        "Id": "1",
        "LineNum": 1,
        "Description": "An employee has worked 3 hours for a customer at an hourly rate of 20",
        "Amount": "{{Amount}}",
        "DetailType": "SalesItemLineDetail",
        "SalesItemLineDetail": {
          "ItemRef": {
            "value": "{{ItemRefValue}}",
            "name": "{{ItemRefName}}"
          },
          "UnitPrice": "{{HourlyRate}}",
          "Qty": "{{HoursWorked}}"
        }
      },
      "type": "object",
      "properties": {
        "Id": {
          "type": "string"
        },
        "LineNum": {
          "type": "integer",
          "format": "int32"
        },
        "Description": {
          "type": "string"
        },
        "Amount": {
          "type": "string"
        },
        "DetailType": {
          "type": "string"
        },
        "SalesItemLineDetail": {
          "$ref": "#/definitions/SalesItemLineDetail2"
        },
        "SubTotalLineDetail": {
          "type": "object"
        }
      },
      "required": [
        "DetailType"
      ]
    },
    "SalesItemLineDetail2": {
      "title": "SalesItemLineDetail2",
      "example": {
        "ItemRef": {
          "value": "{{ItemRefValue}}",
          "name": "{{ItemRefName}}"
        },
        "UnitPrice": "{{HourlyRate}}",
        "Qty": "{{HoursWorked}}"
      },
      "type": "object",
      "properties": {
        "ItemRef": {
          "$ref": "#/definitions/ItemRef"
        },
        "UnitPrice": {
          "type": "string"
        },
        "Qty": {
          "type": "string"
        }
      },
      "required": [
        "ItemRef",
        "UnitPrice",
        "Qty"
      ]
    },
    "Account-CreateExpenseRequest": {
      "title": "Account-CreateExpenseRequest",
      "example": {
        "AccountType": "Expense",
        "Name": "ExpenseAccount - {{$guid}}"
      },
      "type": "object",
      "properties": {
        "AccountType": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": [
        "AccountType",
        "Name"
      ]
    },
    "Purchase-Create-Request": {
      "title": "Purchase-Create-Request",
      "example": {
        "AccountRef": {
          "value": "{{BankAccountId}}",
          "name": "{{BankAccountName}}"
        },
        "PaymentType": "CreditCard",
        "Line": [
          {
            "Amount": 10.0,
            "DetailType": "AccountBasedExpenseLineDetail",
            "AccountBasedExpenseLineDetail": {
              "AccountRef": {
                "name": "{{AccountName}}",
                "value": "{{AccountId}}"
              }
            }
          }
        ]
      },
      "type": "object",
      "properties": {
        "AccountRef": {
          "$ref": "#/definitions/AccountRef1"
        },
        "PaymentType": {
          "type": "string"
        },
        "Line": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Line6"
          }
        }
      },
      "required": [
        "AccountRef",
        "PaymentType",
        "Line"
      ]
    },
    "AccountRef1": {
      "title": "AccountRef1",
      "example": {
        "value": "{{BankAccountId}}",
        "name": "{{BankAccountName}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        },
        "name": {
          "type": "string"
        }
      },
      "required": [
        "value",
        "name"
      ]
    },
    "Line6": {
      "title": "Line6",
      "example": {
        "Amount": 10.0,
        "DetailType": "AccountBasedExpenseLineDetail",
        "AccountBasedExpenseLineDetail": {
          "AccountRef": {
            "name": "{{AccountName}}",
            "value": "{{AccountId}}"
          }
        }
      },
      "type": "object",
      "properties": {
        "Amount": {
          "type": "number",
          "format": "double"
        },
        "DetailType": {
          "type": "string"
        },
        "AccountBasedExpenseLineDetail": {
          "$ref": "#/definitions/AccountBasedExpenseLineDetail1"
        }
      },
      "required": [
        "Amount",
        "DetailType",
        "AccountBasedExpenseLineDetail"
      ]
    },
    "AccountBasedExpenseLineDetail1": {
      "title": "AccountBasedExpenseLineDetail1",
      "example": {
        "AccountRef": {
          "name": "{{AccountName}}",
          "value": "{{AccountId}}"
        }
      },
      "type": "object",
      "properties": {
        "AccountRef": {
          "$ref": "#/definitions/AccountRef1"
        }
      },
      "required": [
        "AccountRef"
      ]
    },
    "Account-CreateBankRequest": {
      "title": "Account-CreateBankRequest",
      "example": {
        "AccountType": "Bank",
        "Name": "BankAccount - {{$guid}}"
      },
      "type": "object",
      "properties": {
        "AccountType": {
          "type": "string"
        },
        "Name": {
          "type": "string"
        }
      },
      "required": [
        "AccountType",
        "Name"
      ]
    }
  },
  "security": [
    {
      "auth": []
    }
  ],
  "tags": [
    {
      "name": "Create a BillPayment against a Vendor's Bill",
      "description": "Pay Bills - This orchestration contains the following flow of calls.  1. Create an account 2.  Create a vendor  3. Create an bill for a vendor and the account created  4. Create a payment for the bill"
    },
    {
      "name": "Create a ReceivePayment against a Customer's Invoice",
      "description": "Create Payment - This orchestration contains the following flow of calls.  1. Create a customer 2.  Create an item  3. Create an invoice for a transaction between the customer and the item.  4. Create payment for the amount owed on invoice"
    },
    {
      "name": "Create a SalesReceipt for a Customer",
      "description": "Create Receipt - This orchestration contains the following flow of calls.  1. Create a customer 2.  Create an item  3. Create a reciept for the transaction between the customer and the item."
    },
    {
      "name": "Create a Time-Activity for an Employee",
      "description": "Create a TimeActivity - This orchestration contains the following flow of calls.  1. Create an employee 2.  Create a customer for whom the employee will work for  3. Create a Time Activity which indicates the that the employee worked for the customer and how many hours and the hourly rate of the employee.  4. Create an Invoice for a TimeActivity.  In this scenario the hours worked, hourly rate, time activity id are all passed from the TimeActivity Create call.\n\nOne note to make, in this particular sandbox company, no tax has been set up.  If tax has been enabled, please include the following in the request:\n\n\"TxnTaxDetail\": {\n     \"TotalTax\": 0,\n     \"TaxLine\": [\n       {\n         \"Amount\": 0,\n         \"DetailType\": \"TaxLineDetail\",\n         \"TaxLineDetail\": {\n           \"TaxRateRef\": {\n             \"value\": \"2\"\n           },\n           \"PercentBased\": true,\n           \"TaxPercent\": 0,\n           \"NetAmountTaxable\": 160.0\n         }\n       }\n    }"
    },
    {
      "name": "Create an Expense for a Vendor",
      "description": "Create an Expense - This orchestration contains the following flow of calls.  1. Create a bank account 2. Create an expense account 3. Create a purchase expense linked to the bank account"
    },
    {
      "name": "Create an Invoice for a Customer",
      "description": "Create an Invoice - This orchestration contains the following flow of calls.  \n\n1. Create a customer \n2. Create an item  \n3. Create an invoice for a transaction between the customer and the item."
    }
  ]
}