{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Users (Okta API)",
    "description": "The [Okta User API](/docs/api/rest/users.html) provides operations to manage users in your organization.",
    "contact": {}
  },
  "host": "example.com",
  "basePath": "/api/v1",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/users": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Create User with Password & Recovery Question",
        "tags": [
          "Create User"
        ],
        "operationId": "CreateUserwithPassword&RecoveryQuestion",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "activate",
            "in": "query",
            "required": true,
            "type": "boolean",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateUserwithPassword%26RecoveryQuestionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "description": "TODO: Add Description",
        "summary": "List Users",
        "tags": [
          "List Users"
        ],
        "operationId": "ListUsers",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "limit",
            "in": "query",
            "required": true,
            "type": "integer",
            "format": "int32",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}": {
      "put": {
        "description": "TODO: Add Description",
        "summary": "Set Password",
        "tags": [
          "Credential Operations"
        ],
        "operationId": "SetPassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SetPasswordRequest"
            }
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get User",
        "tags": [
          "Misc"
        ],
        "operationId": "GetUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/credentials/change_password": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Change Password",
        "tags": [
          "Credential Operations"
        ],
        "operationId": "ChangePassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ChangePasswordRequest"
            }
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/credentials/change_recovery_question": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Change Recovery Question",
        "tags": [
          "Credential Operations"
        ],
        "operationId": "ChangeRecoveryQuestion",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ChangeRecoveryQuestionRequest"
            }
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/credentials/forgot_password": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Forgot Password (Validate Security Answer)",
        "tags": [
          "Credential Operations"
        ],
        "operationId": "ForgotPassword(ValidateSecurityAnswer)",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sendEmail",
            "in": "query",
            "required": true,
            "type": "boolean",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ForgotPassword%28ValidateSecurityAnswer%29Request"
            }
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/activate": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Activate User",
        "tags": [
          "Lifecycle Operations"
        ],
        "operationId": "ActivateUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sendEmail",
            "in": "query",
            "required": true,
            "type": "boolean",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/deactivate": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Deactivate User",
        "tags": [
          "Lifecycle Operations"
        ],
        "operationId": "DeactivateUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/unlock": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Unlock User",
        "tags": [
          "Lifecycle Operations"
        ],
        "operationId": "UnlockUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/expire_password": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Expire Password",
        "tags": [
          "Lifecycle Operations"
        ],
        "operationId": "ExpirePassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/reset_password": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Reset Password",
        "tags": [
          "Lifecycle Operations"
        ],
        "operationId": "ResetPassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "sendEmail",
            "in": "query",
            "required": true,
            "type": "boolean",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/suspend": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Suspend User",
        "tags": [
          "Lifecycle Operations"
        ],
        "operationId": "SuspendUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/unsuspend": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Unsuspend User",
        "tags": [
          "Lifecycle Operations"
        ],
        "operationId": "UnsuspendUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/lifecycle/reset_factors": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Reset Factors",
        "tags": [
          "Misc"
        ],
        "operationId": "ResetFactors",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/me": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get Current User",
        "tags": [
          "Misc"
        ],
        "operationId": "GetCurrentUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/appLinks": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get Assigned App Links",
        "tags": [
          "Misc"
        ],
        "operationId": "GetAssignedAppLinks",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/groups": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get Groups for User",
        "tags": [
          "Misc"
        ],
        "operationId": "GetGroupsforUser",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/users/{userId}/sessions": {
      "delete": {
        "description": "TODO: Add Description",
        "summary": "Clear User Sessions",
        "tags": [
          "Misc"
        ],
        "operationId": "ClearUserSessions",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "definitions": {
    "CreateUserwithPassword&RecoveryQuestionRequest": {
      "title": "CreateUserwithPassword&RecoveryQuestionRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        },
        "credentials": {
          "password": {
            "value": "{{password}}"
          },
          "recovery_question": {
            "question": "Who's a major player in the cowboy scene?",
            "answer": "Annie Oakley"
          }
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials"
        }
      },
      "required": [
        "profile",
        "credentials"
      ]
    },
    "Profile": {
      "title": "Profile",
      "example": {
        "firstName": "Isaac",
        "lastName": "Brock",
        "email": "isaac@{{email-suffix}}",
        "login": "isaac@{{email-suffix}}"
      },
      "type": "object",
      "properties": {
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "login": {
          "type": "string"
        }
      },
      "required": [
        "firstName",
        "lastName",
        "email",
        "login"
      ]
    },
    "Credentials": {
      "title": "Credentials",
      "example": {
        "password": {
          "value": "{{password}}"
        },
        "recovery_question": {
          "question": "Who's a major player in the cowboy scene?",
          "answer": "Annie Oakley"
        }
      },
      "type": "object",
      "properties": {
        "password": {
          "$ref": "#/definitions/Password"
        },
        "recovery_question": {
          "$ref": "#/definitions/RecoveryQuestion"
        }
      },
      "required": [
        "password",
        "recovery_question"
      ]
    },
    "Password": {
      "title": "Password",
      "example": {
        "value": "{{password}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "RecoveryQuestion": {
      "title": "RecoveryQuestion",
      "example": {
        "question": "Who's a major player in the cowboy scene?",
        "answer": "Annie Oakley"
      },
      "type": "object",
      "properties": {
        "question": {
          "type": "string"
        },
        "answer": {
          "type": "string"
        }
      },
      "required": [
        "question",
        "answer"
      ]
    },
    "CreateActivatedUserwithPassword&RecoveryQuestionRequest": {
      "title": "CreateActivatedUserwithPassword&RecoveryQuestionRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        },
        "credentials": {
          "password": {
            "value": "{{password}}"
          },
          "recovery_question": {
            "question": "Who's a major player in the cowboy scene?",
            "answer": "Annie Oakley"
          }
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials"
        }
      },
      "required": [
        "profile",
        "credentials"
      ]
    },
    "CreateUserwithoutCredentialsRequest": {
      "title": "CreateUserwithoutCredentialsRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        }
      },
      "required": [
        "profile"
      ]
    },
    "CreateActivatedUserwithoutCredentialsRequest": {
      "title": "CreateActivatedUserwithoutCredentialsRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        }
      },
      "required": [
        "profile"
      ]
    },
    "CreateUserwithPasswordRequest": {
      "title": "CreateUserwithPasswordRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        },
        "credentials": {
          "password": {
            "value": "{{password}}"
          }
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials2"
        }
      },
      "required": [
        "profile",
        "credentials"
      ]
    },
    "Credentials2": {
      "title": "Credentials2",
      "example": {
        "password": {
          "value": "{{password}}"
        }
      },
      "type": "object",
      "properties": {
        "password": {
          "$ref": "#/definitions/Password"
        }
      },
      "required": [
        "password"
      ]
    },
    "CreateActivatedUserwithPasswordRequest": {
      "title": "CreateActivatedUserwithPasswordRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        },
        "credentials": {
          "password": {
            "value": "{{password}}"
          }
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials2"
        }
      },
      "required": [
        "profile",
        "credentials"
      ]
    },
    "CreateUserwithRecoveryQuestionRequest": {
      "title": "CreateUserwithRecoveryQuestionRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        },
        "credentials": {
          "recovery_question": {
            "question": "Who's a major player in the cowboy scene?",
            "answer": "Annie Oakley"
          }
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials4"
        }
      },
      "required": [
        "profile",
        "credentials"
      ]
    },
    "Credentials4": {
      "title": "Credentials4",
      "example": {
        "recovery_question": {
          "question": "Who's a major player in the cowboy scene?",
          "answer": "Annie Oakley"
        }
      },
      "type": "object",
      "properties": {
        "recovery_question": {
          "$ref": "#/definitions/RecoveryQuestion"
        }
      },
      "required": [
        "recovery_question"
      ]
    },
    "CreateActivatedUserwithRecoveryQuestionRequest": {
      "title": "CreateActivatedUserwithRecoveryQuestionRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        },
        "credentials": {
          "recovery_question": {
            "question": "Who's a major player in the cowboy scene?",
            "answer": "Annie Oakley"
          }
        }
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials4"
        }
      },
      "required": [
        "profile",
        "credentials"
      ]
    },
    "CreateUserinGroupRequest": {
      "title": "CreateUserinGroupRequest",
      "example": {
        "profile": {
          "firstName": "Isaac",
          "lastName": "Brock",
          "email": "isaac@{{email-suffix}}",
          "login": "isaac@{{email-suffix}}"
        },
        "groupIds": [
          "{{groupId}}"
        ]
      },
      "type": "object",
      "properties": {
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "groupIds": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "profile",
        "groupIds"
      ]
    },
    "SetPasswordRequest": {
      "title": "SetPasswordRequest",
      "example": {
        "credentials": {
          "password": {
            "value": "{{password}}"
          }
        }
      },
      "type": "object",
      "properties": {
        "credentials": {
          "$ref": "#/definitions/Credentials2"
        }
      },
      "required": [
        "credentials"
      ]
    },
    "ChangePasswordRequest": {
      "title": "ChangePasswordRequest",
      "example": {
        "oldPassword": {
          "value": "{{password}}"
        },
        "newPassword": {
          "value": "uTVM,TPw55"
        }
      },
      "type": "object",
      "properties": {
        "oldPassword": {
          "$ref": "#/definitions/OldPassword"
        },
        "newPassword": {
          "$ref": "#/definitions/NewPassword"
        }
      },
      "required": [
        "oldPassword",
        "newPassword"
      ]
    },
    "OldPassword": {
      "title": "OldPassword",
      "example": {
        "value": "{{password}}"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "NewPassword": {
      "title": "NewPassword",
      "example": {
        "value": "uTVM,TPw55"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "SetRecoveryCredentialRequest": {
      "title": "SetRecoveryCredentialRequest",
      "example": {
        "credentials": {
          "recovery_question": {
            "question": "Who's a major player in the cowboy scene?",
            "answer": "Annie Oakley"
          }
        }
      },
      "type": "object",
      "properties": {
        "credentials": {
          "$ref": "#/definitions/Credentials4"
        }
      },
      "required": [
        "credentials"
      ]
    },
    "ChangeRecoveryQuestionRequest": {
      "title": "ChangeRecoveryQuestionRequest",
      "example": {
        "password": {
          "value": "{{password}}"
        },
        "recovery_question": {
          "question": "What happens when I update my question",
          "answer": "My recovery credentials are updated"
        }
      },
      "type": "object",
      "properties": {
        "password": {
          "$ref": "#/definitions/Password"
        },
        "recovery_question": {
          "$ref": "#/definitions/RecoveryQuestion"
        }
      },
      "required": [
        "password",
        "recovery_question"
      ]
    },
    "ForgotPassword(ValidateSecurityAnswer)Request": {
      "title": "ForgotPassword(ValidateSecurityAnswer)Request",
      "example": {
        "password": {
          "value": "{{password}}"
        },
        "recovery_question": {
          "answer": "Annie Oakley"
        }
      },
      "type": "object",
      "properties": {
        "password": {
          "$ref": "#/definitions/Password"
        },
        "recovery_question": {
          "$ref": "#/definitions/RecoveryQuestion6"
        }
      },
      "required": [
        "password",
        "recovery_question"
      ]
    },
    "RecoveryQuestion6": {
      "title": "RecoveryQuestion6",
      "example": {
        "answer": "Annie Oakley"
      },
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        }
      },
      "required": [
        "answer"
      ]
    }
  },
  "tags": [
    {
      "name": "Create User"
    },
    {
      "name": "Credential Operations"
    },
    {
      "name": "Lifecycle Operations"
    },
    {
      "name": "List Users"
    },
    {
      "name": "Misc",
      "description": ""
    }
  ]
}