{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Client Registration (Okta API)",
    "description": "TODO: Add Description",
    "contact": {}
  },
  "host": "example.com",
  "basePath": "/",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/api/v1/apps": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Create App",
        "tags": [
          "Apps API"
        ],
        "operationId": "CreateApp",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateAppRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "description": "TODO: Add Description",
        "summary": "List Apps",
        "tags": [
          "Apps API"
        ],
        "operationId": "ListApps",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/api/v1/apps/{appId}": {
      "put": {
        "description": "TODO: Add Description",
        "summary": "Update App",
        "tags": [
          "Apps API"
        ],
        "operationId": "UpdateApp",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateAppRequest"
            }
          },
          {
            "name": "appId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/.well-known/logo": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get Logo",
        "tags": [
          "Misc"
        ],
        "operationId": "GetLogo",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/oauth2/v1/clients": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "List Clients",
        "tags": [
          "Misc"
        ],
        "operationId": "ListClients",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "post": {
        "description": "TODO: Add Description",
        "summary": "Create Client",
        "tags": [
          "Misc"
        ],
        "operationId": "CreateClient",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreateClientRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/oauth2/v1/clients/{clientId}": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get Client",
        "tags": [
          "Misc"
        ],
        "operationId": "GetClient",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "clientId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "description": "TODO: Add Description",
        "summary": "Update Client",
        "tags": [
          "Misc"
        ],
        "operationId": "UpdateClient",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateClientRequest"
            }
          },
          {
            "name": "clientId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "description": "TODO: Add Description",
        "summary": "Delete Client",
        "tags": [
          "Misc"
        ],
        "operationId": "DeleteClient",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "clientId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/oauth2/v1/clients/{clientId}/lifecycle/newSecret": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Generate New Client Secret",
        "tags": [
          "Misc"
        ],
        "operationId": "GenerateNewClientSecret",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "clientId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "definitions": {
    "CreateAppRequest": {
      "title": "CreateAppRequest",
      "example": {
        "name": "oidc_client",
        "label": "Sample Client",
        "signOnMode": "OPENID_CONNECT",
        "credentials": {
          "oauthClient": {
            "token_endpoint_auth_method": "client_secret_post"
          }
        },
        "settings": {
          "oauthClient": {
            "client_uri": "http://localhost:8080",
            "logo_uri": "http://developer.okta.com/assets/images/logo-new.png",
            "redirect_uris": [
              "https://example.com/oauth2/callback",
              "myapp://callback"
            ],
            "response_types": [
              "token",
              "id_token",
              "code"
            ],
            "grant_types": [
              "implicit",
              "authorization_code"
            ],
            "application_type": "native"
          }
        }
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "signOnMode": {
          "type": "string"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials"
        },
        "settings": {
          "$ref": "#/definitions/Settings"
        }
      },
      "required": [
        "name",
        "label",
        "signOnMode",
        "credentials",
        "settings"
      ]
    },
    "Credentials": {
      "title": "Credentials",
      "example": {
        "oauthClient": {
          "token_endpoint_auth_method": "client_secret_post"
        }
      },
      "type": "object",
      "properties": {
        "oauthClient": {
          "$ref": "#/definitions/OauthClient"
        }
      },
      "required": [
        "oauthClient"
      ]
    },
    "OauthClient": {
      "title": "OauthClient",
      "example": {
        "token_endpoint_auth_method": "client_secret_post"
      },
      "type": "object",
      "properties": {
        "token_endpoint_auth_method": {
          "type": "string"
        }
      },
      "required": [
        "token_endpoint_auth_method"
      ]
    },
    "Settings": {
      "title": "Settings",
      "example": {
        "oauthClient": {
          "client_uri": "http://localhost:8080",
          "logo_uri": "http://developer.okta.com/assets/images/logo-new.png",
          "redirect_uris": [
            "https://example.com/oauth2/callback",
            "myapp://callback"
          ],
          "response_types": [
            "token",
            "id_token",
            "code"
          ],
          "grant_types": [
            "implicit",
            "authorization_code"
          ],
          "application_type": "native"
        }
      },
      "type": "object",
      "properties": {
        "oauthClient": {
          "$ref": "#/definitions/OauthClient1"
        }
      },
      "required": [
        "oauthClient"
      ]
    },
    "OauthClient1": {
      "title": "OauthClient1",
      "example": {
        "client_uri": "http://localhost:8080",
        "logo_uri": "http://developer.okta.com/assets/images/logo-new.png",
        "redirect_uris": [
          "https://example.com/oauth2/callback",
          "myapp://callback"
        ],
        "response_types": [
          "token",
          "id_token",
          "code"
        ],
        "grant_types": [
          "implicit",
          "authorization_code"
        ],
        "application_type": "native"
      },
      "type": "object",
      "properties": {
        "client_uri": {
          "type": "string"
        },
        "logo_uri": {
          "type": "string"
        },
        "redirect_uris": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "response_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "grant_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "application_type": {
          "type": "string"
        }
      },
      "required": [
        "client_uri",
        "logo_uri",
        "redirect_uris",
        "response_types",
        "grant_types",
        "application_type"
      ]
    },
    "UpdateAppRequest": {
      "title": "UpdateAppRequest",
      "example": {
        "id": "{{appId}}",
        "name": "oidc_client",
        "label": "Sample Client",
        "signOnMode": "OPENID_CONNECT",
        "credentials": {
          "signing": {
            "kid": "cg4-_A_ifCK7fsKIKjHP27P0JGeuhnHHKEID1yXy42M"
          },
          "oauthClient": {
            "client_id": "0oa1hm4POxgJM6CPu0g4",
            "client_secret": "5jVbn2W72FOAWeQCg7-s_PA0aLqHWjHvUCt2xk-z",
            "token_endpoint_auth_method": "client_secret_post"
          }
        },
        "settings": {
          "oauthClient": {
            "client_uri": "http://localhost:8080",
            "logo_uri": "http://developer.okta.com/assets/images/logo-new.png",
            "redirect_uris": [
              "https://example.com/oauth2/callback",
              "myapp://callback"
            ],
            "response_types": [
              "token",
              "id_token",
              "code"
            ],
            "grant_types": [
              "implicit",
              "authorization_code"
            ],
            "application_type": "native"
          }
        },
        "profile": {
          "whitelist": [
            "{{groupId}}"
          ]
        }
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "label": {
          "type": "string"
        },
        "signOnMode": {
          "type": "string"
        },
        "credentials": {
          "$ref": "#/definitions/Credentials1"
        },
        "settings": {
          "$ref": "#/definitions/Settings"
        },
        "profile": {
          "$ref": "#/definitions/Profile"
        }
      },
      "required": [
        "id",
        "name",
        "label",
        "signOnMode",
        "credentials",
        "settings",
        "profile"
      ]
    },
    "Credentials1": {
      "title": "Credentials1",
      "example": {
        "signing": {
          "kid": "cg4-_A_ifCK7fsKIKjHP27P0JGeuhnHHKEID1yXy42M"
        },
        "oauthClient": {
          "client_id": "0oa1hm4POxgJM6CPu0g4",
          "client_secret": "5jVbn2W72FOAWeQCg7-s_PA0aLqHWjHvUCt2xk-z",
          "token_endpoint_auth_method": "client_secret_post"
        }
      },
      "type": "object",
      "properties": {
        "signing": {
          "$ref": "#/definitions/Signing"
        },
        "oauthClient": {
          "$ref": "#/definitions/OauthClient2"
        }
      },
      "required": [
        "signing",
        "oauthClient"
      ]
    },
    "Signing": {
      "title": "Signing",
      "example": {
        "kid": "cg4-_A_ifCK7fsKIKjHP27P0JGeuhnHHKEID1yXy42M"
      },
      "type": "object",
      "properties": {
        "kid": {
          "type": "string"
        }
      },
      "required": [
        "kid"
      ]
    },
    "OauthClient2": {
      "title": "OauthClient2",
      "example": {
        "client_id": "0oa1hm4POxgJM6CPu0g4",
        "client_secret": "5jVbn2W72FOAWeQCg7-s_PA0aLqHWjHvUCt2xk-z",
        "token_endpoint_auth_method": "client_secret_post"
      },
      "type": "object",
      "properties": {
        "client_id": {
          "type": "string"
        },
        "client_secret": {
          "type": "string"
        },
        "token_endpoint_auth_method": {
          "type": "string"
        }
      },
      "required": [
        "client_id",
        "client_secret",
        "token_endpoint_auth_method"
      ]
    },
    "Profile": {
      "title": "Profile",
      "example": {
        "whitelist": [
          "{{groupId}}"
        ]
      },
      "type": "object",
      "properties": {
        "whitelist": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      },
      "required": [
        "whitelist"
      ]
    },
    "CreateClientRequest": {
      "title": "CreateClientRequest",
      "example": {
        "client_name": "Web client",
        "redirect_uris": [
          "https://httpbin.org/get"
        ],
        "response_types": [
          "code",
          "token",
          "id_token"
        ],
        "grant_types": [
          "refresh_token",
          "authorization_code",
          "implicit"
        ],
        "token_endpoint_auth_method": "client_secret_basic",
        "application_type": "web"
      },
      "type": "object",
      "properties": {
        "client_name": {
          "type": "string"
        },
        "redirect_uris": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "response_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "grant_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "token_endpoint_auth_method": {
          "type": "string"
        },
        "application_type": {
          "type": "string"
        }
      },
      "required": [
        "client_name",
        "redirect_uris",
        "response_types",
        "grant_types",
        "token_endpoint_auth_method",
        "application_type"
      ]
    },
    "UpdateClientRequest": {
      "title": "UpdateClientRequest",
      "example": {
        "client_id": "{{clientId}}",
        "client_name": "Web client",
        "redirect_uris": [
          "https://httpbin.org/get"
        ],
        "response_types": [
          "code",
          "token",
          "id_token"
        ],
        "grant_types": [
          "refresh_token",
          "authorization_code",
          "implicit"
        ],
        "token_endpoint_auth_method": "client_secret_basic",
        "application_type": "web"
      },
      "type": "object",
      "properties": {
        "client_id": {
          "type": "string"
        },
        "client_name": {
          "type": "string"
        },
        "redirect_uris": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "response_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "grant_types": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "token_endpoint_auth_method": {
          "type": "string"
        },
        "application_type": {
          "type": "string"
        }
      },
      "required": [
        "client_id",
        "client_name",
        "redirect_uris",
        "response_types",
        "grant_types",
        "token_endpoint_auth_method",
        "application_type"
      ]
    }
  },
  "tags": [
    {
      "name": "Apps API"
    },
    {
      "name": "Misc",
      "description": ""
    }
  ]
}