{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Inline Hooks",
    "description": "APIs to use for Okta's Inline Hooks features",
    "contact": {}
  },
  "host": "example.com",
  "basePath": "/api/v1",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/inlineHooks": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "List all inline hooks",
        "tags": [
          "Misc"
        ],
        "operationId": "Listallinlinehooks",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "post": {
        "description": "TODO: Add Description",
        "summary": "Create new inline hook",
        "tags": [
          "Misc"
        ],
        "operationId": "Createnewinlinehook",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CreatenewinlinehookRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/inlineHooks/{inlineHookId}": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get inline hook by id",
        "tags": [
          "Misc"
        ],
        "operationId": "Getinlinehookbyid",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "inlineHookId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "description": "TODO: Add Description",
        "summary": "Delete an inline hook",
        "tags": [
          "Misc"
        ],
        "operationId": "Deleteaninlinehook",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "inlineHookId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "put": {
        "description": "TODO: Add Description",
        "summary": "Update existing inline hook",
        "tags": [
          "Misc"
        ],
        "operationId": "Updateexistinginlinehook",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UpdateexistinginlinehookRequest"
            }
          },
          {
            "name": "inlineHookId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/inlineHooks/{inlineHookId}/execute": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Test and execute an inline hook",
        "tags": [
          "Misc"
        ],
        "operationId": "Testandexecuteaninlinehook",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/TestandexecuteaninlinehookRequest"
            }
          },
          {
            "name": "inlineHookId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/inlineHooks/{inlineHookId}/lifecycle/deactivate": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Deactivate an inline hook",
        "tags": [
          "Misc"
        ],
        "operationId": "Deactivateaninlinehook",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "inlineHookId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/inlineHooks/{inlineHookId}/lifecycle/activate": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Activate an inline hook",
        "tags": [
          "Misc"
        ],
        "operationId": "Activateaninlinehook",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "inlineHookId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "definitions": {
    "CreatenewinlinehookRequest": {
      "title": "CreatenewinlinehookRequest",
      "example": {
        "name": "OIDC/OAuth token inline hook",
        "type": "com.okta.oauth2.tokens.transform",
        "version": "1.0.0",
        "channel": {
          "type": "HTTP",
          "version": "1.0.0",
          "config": {
            "uri": "https://example.com",
            "headers": [
              {
                "key": "x-any-key",
                "value": "my-header-value"
              }
            ],
            "method": "POST",
            "authScheme": {
              "type": "HEADER",
              "key": "Authorization",
              "value": "my-shared-secret"
            }
          }
        }
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "channel": {
          "$ref": "#/definitions/Channel"
        }
      },
      "required": [
        "name",
        "type",
        "version",
        "channel"
      ]
    },
    "Channel": {
      "title": "Channel",
      "example": {
        "type": "HTTP",
        "version": "1.0.0",
        "config": {
          "uri": "https://example.com",
          "headers": [
            {
              "key": "x-any-key",
              "value": "my-header-value"
            }
          ],
          "method": "POST",
          "authScheme": {
            "type": "HEADER",
            "key": "Authorization",
            "value": "my-shared-secret"
          }
        }
      },
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "config": {
          "$ref": "#/definitions/Config"
        }
      },
      "required": [
        "type",
        "version",
        "config"
      ]
    },
    "Config": {
      "title": "Config",
      "example": {
        "uri": "https://example.com",
        "headers": [
          {
            "key": "x-any-key",
            "value": "my-header-value"
          }
        ],
        "method": "POST",
        "authScheme": {
          "type": "HEADER",
          "key": "Authorization",
          "value": "my-shared-secret"
        }
      },
      "type": "object",
      "properties": {
        "uri": {
          "type": "string"
        },
        "headers": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Header"
          }
        },
        "method": {
          "type": "string"
        },
        "authScheme": {
          "$ref": "#/definitions/AuthScheme"
        }
      },
      "required": [
        "uri",
        "headers",
        "method",
        "authScheme"
      ]
    },
    "Header": {
      "title": "Header",
      "example": {
        "key": "x-any-key",
        "value": "my-header-value"
      },
      "type": "object",
      "properties": {
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "key",
        "value"
      ]
    },
    "AuthScheme": {
      "title": "AuthScheme",
      "example": {
        "type": "HEADER",
        "key": "Authorization",
        "value": "my-shared-secret"
      },
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "key": {
          "type": "string"
        },
        "value": {
          "type": "string"
        }
      },
      "required": [
        "type",
        "key",
        "value"
      ]
    },
    "TestandexecuteaninlinehookRequest": {
      "title": "TestandexecuteaninlinehookRequest",
      "example": {
        "source": "https://okta.okta.com/oauth2/default/v1/authorize",
        "eventId": "3OWo4oo-QQ-rBWfRyTmQYw",
        "eventTime": "2019-01-15T23:20:47Z",
        "data": {
          "context": {
            "request": {
              "id": "reqv66CbCaCStGEFc8AdfS0ng",
              "method": "GET",
              "url": {
                "value": "https://okta.okta.com/oauth2/default/v1/authorize?scope=openid+profile+email&response_type=token+id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fget&state=foobareere&nonce=asf&client_id=customClientIdNative"
              },
              "ipAddress": "127.0.0.1"
            },
            "protocol": {
              "type": "OAUTH2.0",
              "request": {
                "scope": "openid profile email",
                "state": "foobareere",
                "redirect_uri": "https://httpbin.org/get",
                "response_mode": "fragment",
                "response_type": "token id_token",
                "client_id": "customClientIdNative"
              },
              "issuer": {
                "uri": "https://okta.okta.com/oauth2/default"
              },
              "client": {
                "id": "customClientIdNative",
                "name": "Native client",
                "type": "PUBLIC"
              }
            },
            "session": {
              "id": "102Qoe7t5PcRnSxr8j3I8I6pA",
              "userId": "00uq8tMo3zV0OfJON0g3",
              "login": "administrator1@clouditude.net",
              "createdAt": "2019-01-15T23:17:09Z",
              "expiresAt": "2019-01-16T01:20:46Z",
              "status": "ACTIVE",
              "lastPasswordVerification": "2019-01-15T23:17:09Z",
              "amr": [
                "PASSWORD"
              ],
              "idp": {
                "id": "00oq6kcVwvrDY2YsS0g3",
                "type": "OKTA"
              },
              "mfaActive": false
            },
            "user": {
              "id": "00uq8tMo3zV0OfJON0g3",
              "passwordChanged": "2018-09-11T23:19:12Z",
              "profile": {
                "login": "administrator1@clouditude.net",
                "firstName": "Add-Min",
                "lastName": "O'Cloudy Tud",
                "locale": "en",
                "timeZone": "America/Los_Angeles"
              },
              "_links": {
                "groups": {
                  "href": "https://{yourOktaDomain}/00uq8tMo3zV0OfJON0g3/groups"
                },
                "factors": {
                  "href": "https://{yourOktaDomain}/api/v1/users/00uq8tMo3zV0OfJON0g3/factors"
                }
              }
            },
            "policy": {
              "id": "00pq8lGaLlI8APuqY0g3",
              "rule": {
                "id": "0prq8mLKuKAmavOvq0g3"
              }
            }
          },
          "identity": {
            "claims": {
              "sub": "00uq8tMo3zV0OfJON0g3",
              "name": "Add-Min O'Cloudy Tud",
              "email": "webmaster@clouditude.net",
              "ver": 1,
              "iss": "https://okta.okta.com/oauth2/default",
              "aud": "customClientIdNative",
              "jti": "ID.YxF2whJfB3Eu4ktG_7aClqtCgjDq6ab_hgpiV7-ZZn0",
              "amr": [
                "pwd"
              ],
              "idp": "00oq6kcVwvrDY2YsS0g3",
              "nonce": "asf",
              "preferred_username": "administrator1@clouditude.net",
              "auth_time": 1547594229
            },
            "token": {
              "lifetime": {
                "expiration": 3600
              }
            }
          },
          "access": {
            "claims": {
              "ver": 1,
              "jti": "AT.W-rrB-z-kkZQmHW0e6VS3Or--QfEN_YvoWJa46A7HAA",
              "iss": "https://okta.okta.com/oauth2/default",
              "aud": "api://default",
              "cid": "customClientIdNative",
              "uid": "00uq8tMo3zV0OfJON0g3",
              "sub": "administrator1@clouditude.net",
              "firstName": "Add-Min",
              "preferred_username": "administrator1@clouditude.net"
            },
            "token": {
              "lifetime": {
                "expiration": 3600
              }
            },
            "scopes": {
              "openid": {
                "id": "scpq7bW1cp6dcvrz80g3",
                "action": "GRANT"
              },
              "profile": {
                "id": "scpq7cWJ81CIP5Qkr0g3",
                "action": "GRANT"
              },
              "email": {
                "id": "scpq7dxsoz6LQlRj00g3",
                "action": "GRANT"
              }
            }
          }
        },
        "eventTypeVersion": "1.0",
        "cloudEventVersion": "0.1",
        "contentType": "application/json",
        "eventType": "com.okta.oauth2.tokens.transform"
      },
      "type": "object",
      "properties": {
        "source": {
          "type": "string"
        },
        "eventId": {
          "type": "string"
        },
        "eventTime": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/Data"
        },
        "eventTypeVersion": {
          "type": "string"
        },
        "cloudEventVersion": {
          "type": "string"
        },
        "contentType": {
          "type": "string"
        },
        "eventType": {
          "type": "string"
        }
      },
      "required": [
        "source",
        "eventId",
        "eventTime",
        "data",
        "eventTypeVersion",
        "cloudEventVersion",
        "contentType",
        "eventType"
      ]
    },
    "Data": {
      "title": "Data",
      "example": {
        "context": {
          "request": {
            "id": "reqv66CbCaCStGEFc8AdfS0ng",
            "method": "GET",
            "url": {
              "value": "https://okta.okta.com/oauth2/default/v1/authorize?scope=openid+profile+email&response_type=token+id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fget&state=foobareere&nonce=asf&client_id=customClientIdNative"
            },
            "ipAddress": "127.0.0.1"
          },
          "protocol": {
            "type": "OAUTH2.0",
            "request": {
              "scope": "openid profile email",
              "state": "foobareere",
              "redirect_uri": "https://httpbin.org/get",
              "response_mode": "fragment",
              "response_type": "token id_token",
              "client_id": "customClientIdNative"
            },
            "issuer": {
              "uri": "https://okta.okta.com/oauth2/default"
            },
            "client": {
              "id": "customClientIdNative",
              "name": "Native client",
              "type": "PUBLIC"
            }
          },
          "session": {
            "id": "102Qoe7t5PcRnSxr8j3I8I6pA",
            "userId": "00uq8tMo3zV0OfJON0g3",
            "login": "administrator1@clouditude.net",
            "createdAt": "2019-01-15T23:17:09Z",
            "expiresAt": "2019-01-16T01:20:46Z",
            "status": "ACTIVE",
            "lastPasswordVerification": "2019-01-15T23:17:09Z",
            "amr": [
              "PASSWORD"
            ],
            "idp": {
              "id": "00oq6kcVwvrDY2YsS0g3",
              "type": "OKTA"
            },
            "mfaActive": false
          },
          "user": {
            "id": "00uq8tMo3zV0OfJON0g3",
            "passwordChanged": "2018-09-11T23:19:12Z",
            "profile": {
              "login": "administrator1@clouditude.net",
              "firstName": "Add-Min",
              "lastName": "O'Cloudy Tud",
              "locale": "en",
              "timeZone": "America/Los_Angeles"
            },
            "_links": {
              "groups": {
                "href": "https://{yourOktaDomain}/00uq8tMo3zV0OfJON0g3/groups"
              },
              "factors": {
                "href": "https://{yourOktaDomain}/api/v1/users/00uq8tMo3zV0OfJON0g3/factors"
              }
            }
          },
          "policy": {
            "id": "00pq8lGaLlI8APuqY0g3",
            "rule": {
              "id": "0prq8mLKuKAmavOvq0g3"
            }
          }
        },
        "identity": {
          "claims": {
            "sub": "00uq8tMo3zV0OfJON0g3",
            "name": "Add-Min O'Cloudy Tud",
            "email": "webmaster@clouditude.net",
            "ver": 1,
            "iss": "https://okta.okta.com/oauth2/default",
            "aud": "customClientIdNative",
            "jti": "ID.YxF2whJfB3Eu4ktG_7aClqtCgjDq6ab_hgpiV7-ZZn0",
            "amr": [
              "pwd"
            ],
            "idp": "00oq6kcVwvrDY2YsS0g3",
            "nonce": "asf",
            "preferred_username": "administrator1@clouditude.net",
            "auth_time": 1547594229
          },
          "token": {
            "lifetime": {
              "expiration": 3600
            }
          }
        },
        "access": {
          "claims": {
            "ver": 1,
            "jti": "AT.W-rrB-z-kkZQmHW0e6VS3Or--QfEN_YvoWJa46A7HAA",
            "iss": "https://okta.okta.com/oauth2/default",
            "aud": "api://default",
            "cid": "customClientIdNative",
            "uid": "00uq8tMo3zV0OfJON0g3",
            "sub": "administrator1@clouditude.net",
            "firstName": "Add-Min",
            "preferred_username": "administrator1@clouditude.net"
          },
          "token": {
            "lifetime": {
              "expiration": 3600
            }
          },
          "scopes": {
            "openid": {
              "id": "scpq7bW1cp6dcvrz80g3",
              "action": "GRANT"
            },
            "profile": {
              "id": "scpq7cWJ81CIP5Qkr0g3",
              "action": "GRANT"
            },
            "email": {
              "id": "scpq7dxsoz6LQlRj00g3",
              "action": "GRANT"
            }
          }
        }
      },
      "type": "object",
      "properties": {
        "context": {
          "$ref": "#/definitions/Context"
        },
        "identity": {
          "$ref": "#/definitions/Identity"
        },
        "access": {
          "$ref": "#/definitions/Access"
        }
      },
      "required": [
        "context",
        "identity",
        "access"
      ]
    },
    "Context": {
      "title": "Context",
      "example": {
        "request": {
          "id": "reqv66CbCaCStGEFc8AdfS0ng",
          "method": "GET",
          "url": {
            "value": "https://okta.okta.com/oauth2/default/v1/authorize?scope=openid+profile+email&response_type=token+id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fget&state=foobareere&nonce=asf&client_id=customClientIdNative"
          },
          "ipAddress": "127.0.0.1"
        },
        "protocol": {
          "type": "OAUTH2.0",
          "request": {
            "scope": "openid profile email",
            "state": "foobareere",
            "redirect_uri": "https://httpbin.org/get",
            "response_mode": "fragment",
            "response_type": "token id_token",
            "client_id": "customClientIdNative"
          },
          "issuer": {
            "uri": "https://okta.okta.com/oauth2/default"
          },
          "client": {
            "id": "customClientIdNative",
            "name": "Native client",
            "type": "PUBLIC"
          }
        },
        "session": {
          "id": "102Qoe7t5PcRnSxr8j3I8I6pA",
          "userId": "00uq8tMo3zV0OfJON0g3",
          "login": "administrator1@clouditude.net",
          "createdAt": "2019-01-15T23:17:09Z",
          "expiresAt": "2019-01-16T01:20:46Z",
          "status": "ACTIVE",
          "lastPasswordVerification": "2019-01-15T23:17:09Z",
          "amr": [
            "PASSWORD"
          ],
          "idp": {
            "id": "00oq6kcVwvrDY2YsS0g3",
            "type": "OKTA"
          },
          "mfaActive": false
        },
        "user": {
          "id": "00uq8tMo3zV0OfJON0g3",
          "passwordChanged": "2018-09-11T23:19:12Z",
          "profile": {
            "login": "administrator1@clouditude.net",
            "firstName": "Add-Min",
            "lastName": "O'Cloudy Tud",
            "locale": "en",
            "timeZone": "America/Los_Angeles"
          },
          "_links": {
            "groups": {
              "href": "https://{yourOktaDomain}/00uq8tMo3zV0OfJON0g3/groups"
            },
            "factors": {
              "href": "https://{yourOktaDomain}/api/v1/users/00uq8tMo3zV0OfJON0g3/factors"
            }
          }
        },
        "policy": {
          "id": "00pq8lGaLlI8APuqY0g3",
          "rule": {
            "id": "0prq8mLKuKAmavOvq0g3"
          }
        }
      },
      "type": "object",
      "properties": {
        "request": {
          "$ref": "#/definitions/Request"
        },
        "protocol": {
          "$ref": "#/definitions/Protocol"
        },
        "session": {
          "$ref": "#/definitions/Session"
        },
        "user": {
          "$ref": "#/definitions/User"
        },
        "policy": {
          "$ref": "#/definitions/Policy"
        }
      },
      "required": [
        "request",
        "protocol",
        "session",
        "user",
        "policy"
      ]
    },
    "Request": {
      "title": "Request",
      "example": {
        "id": "reqv66CbCaCStGEFc8AdfS0ng",
        "method": "GET",
        "url": {
          "value": "https://okta.okta.com/oauth2/default/v1/authorize?scope=openid+profile+email&response_type=token+id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fget&state=foobareere&nonce=asf&client_id=customClientIdNative"
        },
        "ipAddress": "127.0.0.1"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "method": {
          "type": "string"
        },
        "url": {
          "$ref": "#/definitions/Url"
        },
        "ipAddress": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "method",
        "url",
        "ipAddress"
      ]
    },
    "Url": {
      "title": "Url",
      "example": {
        "value": "https://okta.okta.com/oauth2/default/v1/authorize?scope=openid+profile+email&response_type=token+id_token&redirect_uri=https%3A%2F%2Fhttpbin.org%2Fget&state=foobareere&nonce=asf&client_id=customClientIdNative"
      },
      "type": "object",
      "properties": {
        "value": {
          "type": "string"
        }
      },
      "required": [
        "value"
      ]
    },
    "Protocol": {
      "title": "Protocol",
      "example": {
        "type": "OAUTH2.0",
        "request": {
          "scope": "openid profile email",
          "state": "foobareere",
          "redirect_uri": "https://httpbin.org/get",
          "response_mode": "fragment",
          "response_type": "token id_token",
          "client_id": "customClientIdNative"
        },
        "issuer": {
          "uri": "https://okta.okta.com/oauth2/default"
        },
        "client": {
          "id": "customClientIdNative",
          "name": "Native client",
          "type": "PUBLIC"
        }
      },
      "type": "object",
      "properties": {
        "type": {
          "type": "string"
        },
        "request": {
          "$ref": "#/definitions/Request1"
        },
        "issuer": {
          "$ref": "#/definitions/Issuer"
        },
        "client": {
          "$ref": "#/definitions/Client"
        }
      },
      "required": [
        "type",
        "request",
        "issuer",
        "client"
      ]
    },
    "Request1": {
      "title": "Request1",
      "example": {
        "scope": "openid profile email",
        "state": "foobareere",
        "redirect_uri": "https://httpbin.org/get",
        "response_mode": "fragment",
        "response_type": "token id_token",
        "client_id": "customClientIdNative"
      },
      "type": "object",
      "properties": {
        "scope": {
          "type": "string"
        },
        "state": {
          "type": "string"
        },
        "redirect_uri": {
          "type": "string"
        },
        "response_mode": {
          "type": "string"
        },
        "response_type": {
          "type": "string"
        },
        "client_id": {
          "type": "string"
        }
      },
      "required": [
        "scope",
        "state",
        "redirect_uri",
        "response_mode",
        "response_type",
        "client_id"
      ]
    },
    "Issuer": {
      "title": "Issuer",
      "example": {
        "uri": "https://okta.okta.com/oauth2/default"
      },
      "type": "object",
      "properties": {
        "uri": {
          "type": "string"
        }
      },
      "required": [
        "uri"
      ]
    },
    "Client": {
      "title": "Client",
      "example": {
        "id": "customClientIdNative",
        "name": "Native client",
        "type": "PUBLIC"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "name",
        "type"
      ]
    },
    "Session": {
      "title": "Session",
      "example": {
        "id": "102Qoe7t5PcRnSxr8j3I8I6pA",
        "userId": "00uq8tMo3zV0OfJON0g3",
        "login": "administrator1@clouditude.net",
        "createdAt": "2019-01-15T23:17:09Z",
        "expiresAt": "2019-01-16T01:20:46Z",
        "status": "ACTIVE",
        "lastPasswordVerification": "2019-01-15T23:17:09Z",
        "amr": [
          "PASSWORD"
        ],
        "idp": {
          "id": "00oq6kcVwvrDY2YsS0g3",
          "type": "OKTA"
        },
        "mfaActive": false
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "userId": {
          "type": "string"
        },
        "login": {
          "type": "string"
        },
        "createdAt": {
          "type": "string"
        },
        "expiresAt": {
          "type": "string"
        },
        "status": {
          "type": "string"
        },
        "lastPasswordVerification": {
          "type": "string"
        },
        "amr": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "idp": {
          "$ref": "#/definitions/Idp"
        },
        "mfaActive": {
          "type": "boolean"
        }
      },
      "required": [
        "id",
        "userId",
        "login",
        "createdAt",
        "expiresAt",
        "status",
        "lastPasswordVerification",
        "amr",
        "idp",
        "mfaActive"
      ]
    },
    "Idp": {
      "title": "Idp",
      "example": {
        "id": "00oq6kcVwvrDY2YsS0g3",
        "type": "OKTA"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "type": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "type"
      ]
    },
    "User": {
      "title": "User",
      "example": {
        "id": "00uq8tMo3zV0OfJON0g3",
        "passwordChanged": "2018-09-11T23:19:12Z",
        "profile": {
          "login": "administrator1@clouditude.net",
          "firstName": "Add-Min",
          "lastName": "O'Cloudy Tud",
          "locale": "en",
          "timeZone": "America/Los_Angeles"
        },
        "_links": {
          "groups": {
            "href": "https://{yourOktaDomain}/00uq8tMo3zV0OfJON0g3/groups"
          },
          "factors": {
            "href": "https://{yourOktaDomain}/api/v1/users/00uq8tMo3zV0OfJON0g3/factors"
          }
        }
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "passwordChanged": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile"
        },
        "_links": {
          "$ref": "#/definitions/Links"
        }
      },
      "required": [
        "id",
        "passwordChanged",
        "profile",
        "_links"
      ]
    },
    "Profile": {
      "title": "Profile",
      "example": {
        "login": "administrator1@clouditude.net",
        "firstName": "Add-Min",
        "lastName": "O'Cloudy Tud",
        "locale": "en",
        "timeZone": "America/Los_Angeles"
      },
      "type": "object",
      "properties": {
        "login": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "lastName": {
          "type": "string"
        },
        "locale": {
          "type": "string"
        },
        "timeZone": {
          "type": "string"
        }
      },
      "required": [
        "login",
        "firstName",
        "lastName",
        "locale",
        "timeZone"
      ]
    },
    "Links": {
      "title": "Links",
      "example": {
        "groups": {
          "href": "https://{yourOktaDomain}/00uq8tMo3zV0OfJON0g3/groups"
        },
        "factors": {
          "href": "https://{yourOktaDomain}/api/v1/users/00uq8tMo3zV0OfJON0g3/factors"
        }
      },
      "type": "object",
      "properties": {
        "groups": {
          "$ref": "#/definitions/Groups"
        },
        "factors": {
          "$ref": "#/definitions/Factors"
        }
      },
      "required": [
        "groups",
        "factors"
      ]
    },
    "Groups": {
      "title": "Groups",
      "example": {
        "href": "https://{yourOktaDomain}/00uq8tMo3zV0OfJON0g3/groups"
      },
      "type": "object",
      "properties": {
        "href": {
          "type": "string"
        }
      },
      "required": [
        "href"
      ]
    },
    "Factors": {
      "title": "Factors",
      "example": {
        "href": "https://{yourOktaDomain}/api/v1/users/00uq8tMo3zV0OfJON0g3/factors"
      },
      "type": "object",
      "properties": {
        "href": {
          "type": "string"
        }
      },
      "required": [
        "href"
      ]
    },
    "Policy": {
      "title": "Policy",
      "example": {
        "id": "00pq8lGaLlI8APuqY0g3",
        "rule": {
          "id": "0prq8mLKuKAmavOvq0g3"
        }
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "rule": {
          "$ref": "#/definitions/Rule"
        }
      },
      "required": [
        "id",
        "rule"
      ]
    },
    "Rule": {
      "title": "Rule",
      "example": {
        "id": "0prq8mLKuKAmavOvq0g3"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        }
      },
      "required": [
        "id"
      ]
    },
    "Identity": {
      "title": "Identity",
      "example": {
        "claims": {
          "sub": "00uq8tMo3zV0OfJON0g3",
          "name": "Add-Min O'Cloudy Tud",
          "email": "webmaster@clouditude.net",
          "ver": 1,
          "iss": "https://okta.okta.com/oauth2/default",
          "aud": "customClientIdNative",
          "jti": "ID.YxF2whJfB3Eu4ktG_7aClqtCgjDq6ab_hgpiV7-ZZn0",
          "amr": [
            "pwd"
          ],
          "idp": "00oq6kcVwvrDY2YsS0g3",
          "nonce": "asf",
          "preferred_username": "administrator1@clouditude.net",
          "auth_time": 1547594229
        },
        "token": {
          "lifetime": {
            "expiration": 3600
          }
        }
      },
      "type": "object",
      "properties": {
        "claims": {
          "$ref": "#/definitions/Claims"
        },
        "token": {
          "$ref": "#/definitions/Token"
        }
      },
      "required": [
        "claims",
        "token"
      ]
    },
    "Claims": {
      "title": "Claims",
      "example": {
        "sub": "00uq8tMo3zV0OfJON0g3",
        "name": "Add-Min O'Cloudy Tud",
        "email": "webmaster@clouditude.net",
        "ver": 1,
        "iss": "https://okta.okta.com/oauth2/default",
        "aud": "customClientIdNative",
        "jti": "ID.YxF2whJfB3Eu4ktG_7aClqtCgjDq6ab_hgpiV7-ZZn0",
        "amr": [
          "pwd"
        ],
        "idp": "00oq6kcVwvrDY2YsS0g3",
        "nonce": "asf",
        "preferred_username": "administrator1@clouditude.net",
        "auth_time": 1547594229
      },
      "type": "object",
      "properties": {
        "sub": {
          "type": "string"
        },
        "name": {
          "type": "string"
        },
        "email": {
          "type": "string"
        },
        "ver": {
          "type": "integer",
          "format": "int32"
        },
        "iss": {
          "type": "string"
        },
        "aud": {
          "type": "string"
        },
        "jti": {
          "type": "string"
        },
        "amr": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "idp": {
          "type": "string"
        },
        "nonce": {
          "type": "string"
        },
        "preferred_username": {
          "type": "string"
        },
        "auth_time": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "sub",
        "name",
        "email",
        "ver",
        "iss",
        "aud",
        "jti",
        "amr",
        "idp",
        "nonce",
        "preferred_username",
        "auth_time"
      ]
    },
    "Token": {
      "title": "Token",
      "example": {
        "lifetime": {
          "expiration": 3600
        }
      },
      "type": "object",
      "properties": {
        "lifetime": {
          "$ref": "#/definitions/Lifetime"
        }
      },
      "required": [
        "lifetime"
      ]
    },
    "Lifetime": {
      "title": "Lifetime",
      "example": {
        "expiration": 3600
      },
      "type": "object",
      "properties": {
        "expiration": {
          "type": "integer",
          "format": "int32"
        }
      },
      "required": [
        "expiration"
      ]
    },
    "Access": {
      "title": "Access",
      "example": {
        "claims": {
          "ver": 1,
          "jti": "AT.W-rrB-z-kkZQmHW0e6VS3Or--QfEN_YvoWJa46A7HAA",
          "iss": "https://okta.okta.com/oauth2/default",
          "aud": "api://default",
          "cid": "customClientIdNative",
          "uid": "00uq8tMo3zV0OfJON0g3",
          "sub": "administrator1@clouditude.net",
          "firstName": "Add-Min",
          "preferred_username": "administrator1@clouditude.net"
        },
        "token": {
          "lifetime": {
            "expiration": 3600
          }
        },
        "scopes": {
          "openid": {
            "id": "scpq7bW1cp6dcvrz80g3",
            "action": "GRANT"
          },
          "profile": {
            "id": "scpq7cWJ81CIP5Qkr0g3",
            "action": "GRANT"
          },
          "email": {
            "id": "scpq7dxsoz6LQlRj00g3",
            "action": "GRANT"
          }
        }
      },
      "type": "object",
      "properties": {
        "claims": {
          "$ref": "#/definitions/Claims1"
        },
        "token": {
          "$ref": "#/definitions/Token"
        },
        "scopes": {
          "$ref": "#/definitions/Scopes"
        }
      },
      "required": [
        "claims",
        "token",
        "scopes"
      ]
    },
    "Claims1": {
      "title": "Claims1",
      "example": {
        "ver": 1,
        "jti": "AT.W-rrB-z-kkZQmHW0e6VS3Or--QfEN_YvoWJa46A7HAA",
        "iss": "https://okta.okta.com/oauth2/default",
        "aud": "api://default",
        "cid": "customClientIdNative",
        "uid": "00uq8tMo3zV0OfJON0g3",
        "sub": "administrator1@clouditude.net",
        "firstName": "Add-Min",
        "preferred_username": "administrator1@clouditude.net"
      },
      "type": "object",
      "properties": {
        "ver": {
          "type": "integer",
          "format": "int32"
        },
        "jti": {
          "type": "string"
        },
        "iss": {
          "type": "string"
        },
        "aud": {
          "type": "string"
        },
        "cid": {
          "type": "string"
        },
        "uid": {
          "type": "string"
        },
        "sub": {
          "type": "string"
        },
        "firstName": {
          "type": "string"
        },
        "preferred_username": {
          "type": "string"
        }
      },
      "required": [
        "ver",
        "jti",
        "iss",
        "aud",
        "cid",
        "uid",
        "sub",
        "firstName",
        "preferred_username"
      ]
    },
    "Scopes": {
      "title": "Scopes",
      "example": {
        "openid": {
          "id": "scpq7bW1cp6dcvrz80g3",
          "action": "GRANT"
        },
        "profile": {
          "id": "scpq7cWJ81CIP5Qkr0g3",
          "action": "GRANT"
        },
        "email": {
          "id": "scpq7dxsoz6LQlRj00g3",
          "action": "GRANT"
        }
      },
      "type": "object",
      "properties": {
        "openid": {
          "$ref": "#/definitions/Openid"
        },
        "profile": {
          "$ref": "#/definitions/Profile1"
        },
        "email": {
          "$ref": "#/definitions/Email"
        }
      },
      "required": [
        "openid",
        "profile",
        "email"
      ]
    },
    "Openid": {
      "title": "Openid",
      "example": {
        "id": "scpq7bW1cp6dcvrz80g3",
        "action": "GRANT"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "action": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "action"
      ]
    },
    "Profile1": {
      "title": "Profile1",
      "example": {
        "id": "scpq7cWJ81CIP5Qkr0g3",
        "action": "GRANT"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "action": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "action"
      ]
    },
    "Email": {
      "title": "Email",
      "example": {
        "id": "scpq7dxsoz6LQlRj00g3",
        "action": "GRANT"
      },
      "type": "object",
      "properties": {
        "id": {
          "type": "string"
        },
        "action": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "action"
      ]
    },
    "UpdateexistinginlinehookRequest": {
      "title": "UpdateexistinginlinehookRequest",
      "example": {
        "name": "OIDC/OAuth token inline hook updated",
        "type": "com.okta.oauth2.tokens.transform",
        "version": "1.0.0",
        "channel": {
          "type": "HTTP",
          "version": "1.0.0",
          "config": {
            "uri": "https://example.com",
            "headers": [
              {
                "key": "x-any-key",
                "value": "my-header-value-updated"
              }
            ],
            "method": "POST",
            "authScheme": {
              "type": "HEADER",
              "key": "Authorization",
              "value": "my-shared-secret-updated"
            }
          }
        }
      },
      "type": "object",
      "properties": {
        "name": {
          "type": "string"
        },
        "type": {
          "type": "string"
        },
        "version": {
          "type": "string"
        },
        "channel": {
          "$ref": "#/definitions/Channel"
        }
      },
      "required": [
        "name",
        "type",
        "version",
        "channel"
      ]
    }
  },
  "tags": [
    {
      "name": "Misc",
      "description": ""
    }
  ]
}