{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Authentication (Okta API)",
    "description": "TODO: Add Description",
    "contact": {}
  },
  "host": "example.com",
  "basePath": "/api/v1",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/users/{userId}/factors/questions": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "List Questions",
        "tags": [
          "Enroll"
        ],
        "operationId": "ListQuestions",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "userId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/factors": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Enroll Question Factor",
        "tags": [
          "Enroll"
        ],
        "operationId": "EnrollQuestionFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/EnrollQuestionFactorRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/factors/{factorId}/lifecycle/activate": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Activate SMS Factor",
        "tags": [
          "Enroll"
        ],
        "operationId": "ActivateSMSFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ActivateSMSFactorRequest"
            }
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/recovery/password": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Forgot Password with Email Factor",
        "tags": [
          "Forgot Password"
        ],
        "operationId": "ForgotPasswordwithEmailFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ForgotPasswordwithEmailFactorRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/recovery/factors/sms/verify": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Verify SMS Recovery Factor",
        "tags": [
          "Forgot Password"
        ],
        "operationId": "VerifySMSRecoveryFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/VerifySMSRecoveryFactorRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/recovery/token": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Verify Recovery Token",
        "tags": [
          "Forgot Password"
        ],
        "operationId": "VerifyRecoveryToken",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/VerifyRecoveryTokenRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/recovery/answer": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Answer Recovery Question",
        "tags": [
          "Forgot Password"
        ],
        "operationId": "AnswerRecoveryQuestion",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/AnswerRecoveryQuestionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/credentials/reset_password": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Reset Password",
        "tags": [
          "Forgot Password"
        ],
        "operationId": "ResetPassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ResetPasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/recovery/unlock": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Unlock Account with Email Factor",
        "tags": [
          "Self-Service Unlock"
        ],
        "operationId": "UnlockAccountwithEmailFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/UnlockAccountwithEmailFactorRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Get Transaction  State",
        "tags": [
          "State Management"
        ],
        "operationId": "GetTransactionState",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/GetTransactionStateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/skip": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Skip Transaction State",
        "tags": [
          "State Management"
        ],
        "operationId": "SkipTransactionState",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SkipTransactionStateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/previous": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Previous Transaction State",
        "tags": [
          "State Management"
        ],
        "operationId": "PreviousTransactionState",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/PreviousTransactionStateRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/cancel": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Cancel Transaction",
        "tags": [
          "State Management"
        ],
        "operationId": "CancelTransaction",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/CancelTransactionRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/factors/{factorId}/verify": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Send SMS Challenge (OTP)",
        "tags": [
          "Verify"
        ],
        "operationId": "SendSMSChallenge(OTP)",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/SendSMSChallenge%28OTP%29Request"
            }
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/factors/{factorId}/verify/resend": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Resend Challenge",
        "tags": [
          "Verify"
        ],
        "operationId": "ResendChallenge",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ResendChallengeRequest"
            }
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/credentials/change_password": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Change Password",
        "tags": [
          "Misc"
        ],
        "operationId": "ChangePassword",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ChangePasswordRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    },
    "/authn/factors/{factorId}/lifecycle/activate/poll": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Poll for Factor enrollment",
        "tags": [
          "Misc"
        ],
        "operationId": "PollforFactorenrollment",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/PollforFactorenrollmentRequest"
            }
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        }
      }
    }
  },
  "definitions": {
    "EnrollQuestionFactorRequest": {
      "title": "EnrollQuestionFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "question",
        "provider": "OKTA",
        "profile": {
          "question": "name_of_first_plush_toy",
          "answer": "blah"
        }
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider",
        "profile"
      ]
    },
    "Profile": {
      "title": "Profile",
      "example": {
        "question": "name_of_first_plush_toy",
        "answer": "blah"
      },
      "type": "object",
      "properties": {
        "question": {
          "type": "string"
        },
        "answer": {
          "type": "string"
        }
      },
      "required": [
        "question",
        "answer"
      ]
    },
    "EnrollSMSFactorRequest": {
      "title": "EnrollSMSFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "sms",
        "provider": "OKTA",
        "profile": {
          "phoneNumber": "+1 415 555 5555"
        }
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile1"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider",
        "profile"
      ]
    },
    "Profile1": {
      "title": "Profile1",
      "example": {
        "phoneNumber": "+1 415 555 5555"
      },
      "type": "object",
      "properties": {
        "phoneNumber": {
          "type": "string"
        }
      },
      "required": [
        "phoneNumber"
      ]
    },
    "EnrollSMSFactorwithNewNumberRequest": {
      "title": "EnrollSMSFactorwithNewNumberRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "sms",
        "provider": "OKTA",
        "profile": {
          "phoneNumber": "+1 415 555 5555"
        }
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile1"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider",
        "profile"
      ]
    },
    "EnrollOktaTOTPFactorRequest": {
      "title": "EnrollOktaTOTPFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "token:software:totp",
        "provider": "OKTA"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider"
      ]
    },
    "EnrollOktaVerifyPushFactorRequest": {
      "title": "EnrollOktaVerifyPushFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "push",
        "provider": "OKTA"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider"
      ]
    },
    "EnrollGoogleAuthenticatorFactorRequest": {
      "title": "EnrollGoogleAuthenticatorFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "token:software:totp",
        "provider": "GOOGLE"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider"
      ]
    },
    "EnrollRSASecurIDFactorRequest": {
      "title": "EnrollRSASecurIDFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "token:hardware",
        "provider": "YUBICO",
        "passCode": "cccccceukngdfgkukfctkcvfidnetljjiknckkcjulji"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider",
        "passCode"
      ]
    },
    "EnrollSymantecVIPFactorRequest": {
      "title": "EnrollSymantecVIPFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "token",
        "provider": "SYMANTEC",
        "profile": {
          "credentialId": "VSMT14393584"
        },
        "passCode": "875498",
        "nextPassCode": "678195"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile3"
        },
        "passCode": {
          "type": "string"
        },
        "nextPassCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider",
        "profile",
        "passCode",
        "nextPassCode"
      ]
    },
    "Profile3": {
      "title": "Profile3",
      "example": {
        "credentialId": "VSMT14393584"
      },
      "type": "object",
      "properties": {
        "credentialId": {
          "type": "string"
        }
      },
      "required": [
        "credentialId"
      ]
    },
    "EnrollYubiKeyFactorRequest": {
      "title": "EnrollYubiKeyFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "token",
        "provider": "RSA",
        "profile": {
          "credentialId": "{{username}}"
        },
        "passCode": "5275875498"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile3"
        },
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider",
        "profile",
        "passCode"
      ]
    },
    "ActivateSMSFactorRequest": {
      "title": "ActivateSMSFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "passCode": "679682"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "passCode"
      ]
    },
    "ActivateTOTPFactorRequest": {
      "title": "ActivateTOTPFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "passCode": "679682"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "passCode"
      ]
    },
    "ActivatePushFactorRequest": {
      "title": "ActivatePushFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "ForgotPasswordwithEmailFactorRequest": {
      "title": "ForgotPasswordwithEmailFactorRequest",
      "example": {
        "username": "{{username}}",
        "factorType": "EMAIL",
        "relayState": "/myapp/some/deep/link/i/want/to/return/to"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "relayState": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "factorType",
        "relayState"
      ]
    },
    "ForgotPasswordwithSMSFactorRequest": {
      "title": "ForgotPasswordwithSMSFactorRequest",
      "example": {
        "username": "{{username}}",
        "factorType": "SMS",
        "relayState": "/myapp/some/deep/link/i/want/to/return/to"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "relayState": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "factorType",
        "relayState"
      ]
    },
    "ForgotPasswordforTrustedApplicationRequest": {
      "title": "ForgotPasswordforTrustedApplicationRequest",
      "example": {
        "username": "{{username}}",
        "relayState": "{{relayState}}"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "relayState": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "relayState"
      ]
    },
    "VerifySMSRecoveryFactorRequest": {
      "title": "VerifySMSRecoveryFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "passCode": "123456"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "passCode"
      ]
    },
    "VerifyRecoveryTokenRequest": {
      "title": "VerifyRecoveryTokenRequest",
      "example": {
        "recoveryToken": "{{recoveryToken}}"
      },
      "type": "object",
      "properties": {
        "recoveryToken": {
          "type": "string"
        }
      },
      "required": [
        "recoveryToken"
      ]
    },
    "AnswerRecoveryQuestionRequest": {
      "title": "AnswerRecoveryQuestionRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "answer": "Annie Oakley"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "answer": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "answer"
      ]
    },
    "ResetPasswordRequest": {
      "title": "ResetPasswordRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "newPassword": "Ch-ch-ch-ch-Chang3s!"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "newPassword"
      ]
    },
    "UnlockAccountwithEmailFactorRequest": {
      "title": "UnlockAccountwithEmailFactorRequest",
      "example": {
        "username": "{{username}}",
        "factorType": "EMAIL",
        "relayState": "/myapp/some/deep/link/i/want/to/return/to"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "relayState": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "factorType",
        "relayState"
      ]
    },
    "UnlockAccountwithSMSFactorRequest": {
      "title": "UnlockAccountwithSMSFactorRequest",
      "example": {
        "username": "{{username}}",
        "factorType": "SMS",
        "relayState": "/myapp/some/deep/link/i/want/to/return/to"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "relayState": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "factorType",
        "relayState"
      ]
    },
    "UnlockAccountwithTrustedApplicationRequest": {
      "title": "UnlockAccountwithTrustedApplicationRequest",
      "example": {
        "username": "{{username}}",
        "relayState": "{{relayState}}"
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "relayState": {
          "type": "string"
        }
      },
      "required": [
        "username",
        "relayState"
      ]
    },
    "GetTransactionStateRequest": {
      "title": "GetTransactionStateRequest",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "SkipTransactionStateRequest": {
      "title": "SkipTransactionStateRequest",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "PreviousTransactionStateRequest": {
      "title": "PreviousTransactionStateRequest",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "CancelTransactionRequest": {
      "title": "CancelTransactionRequest",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "SendSMSChallenge(OTP)Request": {
      "title": "SendSMSChallenge(OTP)Request",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "VerifyQuestionFactorRequest": {
      "title": "VerifyQuestionFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "answer": "Annie Oakley"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "answer": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "answer"
      ]
    },
    "VerifySMSFactorRequest": {
      "title": "VerifySMSFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "passCode": "029656"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "passCode"
      ]
    },
    "VerifyTOTPFactorRequest": {
      "title": "VerifyTOTPFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "passCode": "029656"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "passCode"
      ]
    },
    "VerifyandPollPushFactorRequest": {
      "title": "VerifyandPollPushFactorRequest",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "ResendChallengeRequest": {
      "title": "ResendChallengeRequest",
      "example": {
        "stateToken": "{{stateToken}}"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        }
      },
      "required": [
        "stateToken"
      ]
    },
    "PrimaryAuthenticationRequest": {
      "title": "PrimaryAuthenticationRequest",
      "example": {
        "username": "{{username}}",
        "password": "{{password}}",
        "options": {
          "multiOptionalFactorEnroll": true,
          "warnBeforePasswordExpired": true
        }
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "options": {
          "$ref": "#/definitions/Options"
        }
      },
      "required": [
        "username",
        "password",
        "options"
      ]
    },
    "Options": {
      "title": "Options",
      "example": {
        "multiOptionalFactorEnroll": true,
        "warnBeforePasswordExpired": true
      },
      "type": "object",
      "properties": {
        "multiOptionalFactorEnroll": {
          "type": "boolean"
        },
        "warnBeforePasswordExpired": {
          "type": "boolean"
        }
      },
      "required": [
        "multiOptionalFactorEnroll",
        "warnBeforePasswordExpired"
      ]
    },
    "PrimaryAuthenticationwithTrustedApplicationRequest": {
      "title": "PrimaryAuthenticationwithTrustedApplicationRequest",
      "example": {
        "username": "{{username}}",
        "password": "{{password}}",
        "relayState": "{{relayState}}",
        "options": {
          "multiOptionalFactorEnroll": true,
          "warnBeforePasswordExpired": true
        },
        "context": {
          "deviceToken": "26q43Ak9Eh04p7H6Nnx0m69JqYOrfVBY"
        }
      },
      "type": "object",
      "properties": {
        "username": {
          "type": "string"
        },
        "password": {
          "type": "string"
        },
        "relayState": {
          "type": "string"
        },
        "options": {
          "$ref": "#/definitions/Options"
        },
        "context": {
          "$ref": "#/definitions/Context"
        }
      },
      "required": [
        "username",
        "password",
        "relayState",
        "options",
        "context"
      ]
    },
    "Context": {
      "title": "Context",
      "example": {
        "deviceToken": "26q43Ak9Eh04p7H6Nnx0m69JqYOrfVBY"
      },
      "type": "object",
      "properties": {
        "deviceToken": {
          "type": "string"
        }
      },
      "required": [
        "deviceToken"
      ]
    },
    "ChangePasswordRequest": {
      "title": "ChangePasswordRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "oldPassword": "3EMaPQ7x",
        "newPassword": "Ch-ch-ch-ch-Chang3s!"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "oldPassword": {
          "type": "string"
        },
        "newPassword": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "oldPassword",
        "newPassword"
      ]
    },
    "PollforFactorenrollmentRequest": {
      "title": "PollforFactorenrollmentRequest",
      "example": {
        "stateToken": "{{stateToken}}",
        "factorType": "push",
        "provider": "OKTA"
      },
      "type": "object",
      "properties": {
        "stateToken": {
          "type": "string"
        },
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "required": [
        "stateToken",
        "factorType",
        "provider"
      ]
    }
  },
  "tags": [
    {
      "name": "Enroll"
    },
    {
      "name": "Forgot Password"
    },
    {
      "name": "Self-Service Unlock"
    },
    {
      "name": "State Management"
    },
    {
      "name": "Verify"
    },
    {
      "name": "Misc",
      "description": ""
    }
  ]
}