{
  "swagger": "2.0",
  "info": {
    "version": "1.0",
    "title": "Factors (Okta API)",
    "description": "TODO: Add Description",
    "contact": {}
  },
  "host": "example.com",
  "basePath": "/api/v1/users/DefaultParameterValue",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/factors": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Enroll Okta Security Question Factor",
        "tags": [
          "Factor Lifecycle Operations"
        ],
        "operationId": "EnrollOktaSecurityQuestionFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/EnrollOktaSecurityQuestionFactorRequest"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "get": {
        "description": "TODO: Add Description",
        "summary": "List Factors",
        "tags": [
          "Misc"
        ],
        "operationId": "ListFactors",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/factors/{factorId}/lifecycle/activate": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Activate SMS Factor",
        "tags": [
          "Factor Lifecycle Operations"
        ],
        "operationId": "ActivateSMSFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/ActivateSMSFactorRequest"
            }
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/lifecycle/reset_factors": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Reset All Factors",
        "tags": [
          "Factor Lifecycle Operations"
        ],
        "operationId": "ResetAllFactors",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/factors/{factorId}/verify": {
      "post": {
        "description": "TODO: Add Description",
        "summary": "Verify Question Factor",
        "tags": [
          "Factor Verification Operations"
        ],
        "operationId": "VerifyQuestionFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Body",
            "in": "body",
            "required": true,
            "description": "",
            "schema": {
              "$ref": "#/definitions/VerifyQuestionFactorRequest"
            }
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/factors/{factorId}/transactions/{transactionId}/verify": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Verify Push  Factor",
        "tags": [
          "Factor Verification Operations"
        ],
        "operationId": "VerifyPushFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "transactionId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/factors/{factorId}": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "Get Factor",
        "tags": [
          "Misc"
        ],
        "operationId": "GetFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      },
      "delete": {
        "description": "TODO: Add Description",
        "summary": "Delete Factor",
        "tags": [
          "Misc"
        ],
        "operationId": "DeleteFactor",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "factorId",
            "in": "path",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/factors/catalog": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "List Factors to Enroll",
        "tags": [
          "Misc"
        ],
        "operationId": "ListFactorstoEnroll",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    },
    "/factors/questions": {
      "get": {
        "description": "TODO: Add Description",
        "summary": "List Security Questions",
        "tags": [
          "Misc"
        ],
        "operationId": "ListSecurityQuestions",
        "deprecated": false,
        "produces": [
          "application/json"
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Content-Type",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          },
          {
            "name": "Authorization",
            "in": "header",
            "required": true,
            "type": "string",
            "description": ""
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "headers": {}
          }
        },
        "security": []
      }
    }
  },
  "definitions": {
    "EnrollOktaSecurityQuestionFactorRequest": {
      "title": "EnrollOktaSecurityQuestionFactorRequest",
      "example": {
        "factorType": "question",
        "provider": "OKTA",
        "profile": {
          "question": "disliked_food",
          "answer": "mayonnaise"
        }
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile"
        }
      },
      "required": [
        "factorType",
        "provider",
        "profile"
      ]
    },
    "Profile": {
      "title": "Profile",
      "example": {
        "question": "disliked_food",
        "answer": "mayonnaise"
      },
      "type": "object",
      "properties": {
        "question": {
          "type": "string"
        },
        "answer": {
          "type": "string"
        }
      },
      "required": [
        "question",
        "answer"
      ]
    },
    "EnrollOktaSMSFactorRequest": {
      "title": "EnrollOktaSMSFactorRequest",
      "example": {
        "factorType": "sms",
        "provider": "OKTA",
        "profile": {
          "phoneNumber": "{{phoneNumber}}"
        }
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile1"
        }
      },
      "required": [
        "factorType",
        "provider",
        "profile"
      ]
    },
    "Profile1": {
      "title": "Profile1",
      "example": {
        "phoneNumber": "{{phoneNumber}}"
      },
      "type": "object",
      "properties": {
        "phoneNumber": {
          "type": "string"
        }
      },
      "required": [
        "phoneNumber"
      ]
    },
    "EnrollOktaSMSFactorwithNewNumberRequest": {
      "title": "EnrollOktaSMSFactorwithNewNumberRequest",
      "example": {
        "factorType": "sms",
        "provider": "OKTA",
        "profile": {
          "phoneNumber": "+1-555-415-1337"
        }
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile1"
        }
      },
      "required": [
        "factorType",
        "provider",
        "profile"
      ]
    },
    "EnrollOktaVerifyTOTPFactorRequest": {
      "title": "EnrollOktaVerifyTOTPFactorRequest",
      "example": {
        "factorType": "token:software:totp",
        "provider": "OKTA"
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "required": [
        "factorType",
        "provider"
      ]
    },
    "EnrollOktaVerifyPushFactorRequest": {
      "title": "EnrollOktaVerifyPushFactorRequest",
      "example": {
        "factorType": "push",
        "provider": "OKTA"
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "required": [
        "factorType",
        "provider"
      ]
    },
    "EnrollGoogleAuthenticatorFactorRequest": {
      "title": "EnrollGoogleAuthenticatorFactorRequest",
      "example": {
        "factorType": "token:software:totp",
        "provider": "GOOGLE"
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        }
      },
      "required": [
        "factorType",
        "provider"
      ]
    },
    "EnrollSymantecVIPTokenFactorRequest": {
      "title": "EnrollSymantecVIPTokenFactorRequest",
      "example": {
        "factorType": "token",
        "provider": "SYMANTEC",
        "profile": {
          "credentialId": "VSMT14393584"
        },
        "verify": {
          "passCode": "875498",
          "nextPassCode": "678195"
        }
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile3"
        },
        "verify": {
          "$ref": "#/definitions/Verify"
        }
      },
      "required": [
        "factorType",
        "provider",
        "profile",
        "verify"
      ]
    },
    "Profile3": {
      "title": "Profile3",
      "example": {
        "credentialId": "VSMT14393584"
      },
      "type": "object",
      "properties": {
        "credentialId": {
          "type": "string"
        }
      },
      "required": [
        "credentialId"
      ]
    },
    "Verify": {
      "title": "Verify",
      "example": {
        "passCode": "875498",
        "nextPassCode": "678195"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        },
        "nextPassCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode",
        "nextPassCode"
      ]
    },
    "EnrollRSASecurIDFactorRequest": {
      "title": "EnrollRSASecurIDFactorRequest",
      "example": {
        "factorType": "token",
        "provider": "RSA",
        "profile": {
          "credentialId": "{{username}}"
        },
        "verify": {
          "passCode": "875498"
        }
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "profile": {
          "$ref": "#/definitions/Profile3"
        },
        "verify": {
          "$ref": "#/definitions/Verify1"
        }
      },
      "required": [
        "factorType",
        "provider",
        "profile",
        "verify"
      ]
    },
    "Verify1": {
      "title": "Verify1",
      "example": {
        "passCode": "875498"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode"
      ]
    },
    "EnrollYubiKeyFactorRequest": {
      "title": "EnrollYubiKeyFactorRequest",
      "example": {
        "factorType": "token:hardware",
        "provider": "YUBICO",
        "verify": {
          "passCode": "cccccceukngdfgkukfctkcvfidnetljjiknckkcjulji"
        }
      },
      "type": "object",
      "properties": {
        "factorType": {
          "type": "string"
        },
        "provider": {
          "type": "string"
        },
        "verify": {
          "$ref": "#/definitions/Verify1"
        }
      },
      "required": [
        "factorType",
        "provider",
        "verify"
      ]
    },
    "ActivateSMSFactorRequest": {
      "title": "ActivateSMSFactorRequest",
      "example": {
        "passCode": "309524"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode"
      ]
    },
    "ActivateTOTPFactorRequest": {
      "title": "ActivateTOTPFactorRequest",
      "example": {
        "passCode": "866028"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode"
      ]
    },
    "VerifyQuestionFactorRequest": {
      "title": "VerifyQuestionFactorRequest",
      "example": {
        "answer": "Annie Oakley"
      },
      "type": "object",
      "properties": {
        "answer": {
          "type": "string"
        }
      },
      "required": [
        "answer"
      ]
    },
    "SendSMSChallengeRequest": {
      "title": "SendSMSChallengeRequest",
      "example": {
        "passCode": "382883"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode"
      ]
    },
    "VerifySMSFactorRequest": {
      "title": "VerifySMSFactorRequest",
      "example": {
        "passCode": "382883"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode"
      ]
    },
    "VerifyTOTPFactorRequest": {
      "title": "VerifyTOTPFactorRequest",
      "example": {
        "passCode": "382883"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode"
      ]
    },
    "VerifyTokenFactorRequest": {
      "title": "VerifyTokenFactorRequest",
      "example": {
        "passCode": "382883"
      },
      "type": "object",
      "properties": {
        "passCode": {
          "type": "string"
        }
      },
      "required": [
        "passCode"
      ]
    }
  },
  "tags": [
    {
      "name": "Factor Lifecycle Operations"
    },
    {
      "name": "Factor Verification Operations"
    },
    {
      "name": "Misc",
      "description": ""
    }
  ]
}